packages/deployer/package.json
packages/deployer/src/commands.ts
packages/deployer/src/io.ts
packages/deployer/src/util.ts
packages/deployer/yarn.lock
yarn.lock

Implements #143 
Remaining work to do:
- Bypass verification while debugging, do i need to add an new --debug argument?

Mnemonic verification process

---

packages/validator/README.md

I had a bit of confusion with the last example, so this explanation is meant to clarify my understanding as well as be something I can reference in case I forget :P

Adding explanation to last example in README.md

---

.github/workflows/documentation.yml
.github/workflows/master.yml

Update slack channel to the right one

Fix broken build node14

---

packages/node/__dev__/.env.example
packages/node/__dev__/config.json.example

Updating .env.example and config.example so we can run start-coordinator locally add-hoc using them without need any changes.

updated .env example and config.json

---

packages/deployer/src/config.ts
packages/node/src/config/index.ts

fix for env variables in pre-alpha

---

.github/workflows/build-test.yml
docker/Dockerfile
package.json
packages/admin/package.json
packages/deployer/package.json
packages/deployer/src/cli/commands.ts
packages/node/package.json
yarn.lock

Closes #[222](https://github.com/api3dao/airnode/issues/222)
Using 14.17.1-alpine3.13 in docker/Dockerfile. 
Tested:
Building and running all the tests.
Running dev:invoke locally
Running yarn run cli deploy inside packages/deployer and making sure secrets temp file gets removed

Upgrades Node.js to v14.17.1 (LTS) and also upgrades ts-node and @types/node

---

docker/Dockerfile

Fix deployer Docker build on Windows

---

packages/deployer/config/config.json.example
packages/deployer/src/cli/commands.ts
packages/deployer/src/types.ts
packages/node/__dev__/config.json.example
packages/node/src/types.ts
packages/node/test/fixtures/config/config.ts

Tested by running: 
1. yarn build and yarn test
2. dev:invoke

#411: Remove the id field from config.json

---

packages/deployer/config/config.json.example
packages/deployer/src/cli/commands.ts
packages/deployer/src/evm/config.ts
packages/deployer/src/evm/index.ts
packages/deployer/src/handlers/aws/index.ts
packages/deployer/src/types.ts
packages/deployer/src/utils/files.ts
packages/node/__dev__/config.json.example
packages/node/src/coordinator/calls/coordinated-execution.test.ts
packages/node/src/handlers/start-coordinator.test.ts
packages/node/src/providers/actions.test.ts
packages/node/src/workers/local-handlers.test.ts
packages/node/src/workers/local-handlers.ts
packages/node/test/e2e/client-fulfill.feature.ts
packages/node/test/e2e/no-duplication.feature.ts
packages/node/test/e2e/request-status.feature.ts
packages/node/test/e2e/withdrawals.feature.ts

Revert `config.json` structure back to object

---

packages/admin/src/implementation.ts

Basically the same changes as in https://github.com/api3dao/airnode/pull/440
but the base branch is current `master` and can be merged as of now. We might want to update the npm package as well.
Maybe sometime, we will be able to have better type awareness using typeechain https://github.com/ethereum-ts/TypeChain/issues/440

Fix admin CLI listening for incorrect event

---

packages/admin/src/implementation.ts

Fixes regression bug.
Tests:
Ran e2e test suite.
Notes:
I didn't change the `fulfillWithdrawal` becuase in this particular case we are passing specific values as parameters to the filter.

fix(#427):Admin package is not listening for the correct event

---

packages/deployer/src/cli/index.ts

Fix deployer status code on error

---

packages/operation/README.md
packages/operation/src/config/evm-dev-config.json
packages/operation/src/evm/deploy/account-assignment.ts
packages/operation/src/evm/deploy/airnodes.ts
packages/operation/src/evm/deploy/deployment.ts
packages/operation/src/evm/deploy/funding.ts
packages/operation/src/evm/deploy/requesters.ts
packages/operation/src/evm/deploy/state.ts
packages/operation/src/evm/io.ts
packages/operation/src/evm/requests/make-requests.ts
packages/operation/src/evm/utils.ts
packages/operation/src/scripts/evm-dev-deploy.ts
packages/operation/src/scripts/evm-dev-requests.ts
packages/operation/src/types.ts

Main changes:
1. Renames clients with requesters and requesters with sponsors.
2. No longer sets authorizers on chain and just sets xpub (no needed but nice to have)
3. Updates requester contract reference (MockRrpRequesterFactory)
Tests:
1. ran all steps except for `invoke` since node package is still broken

Fixes operation package

---

packages/deployer/src/cli/commands.ts
packages/deployer/src/infrastructure/index.ts
packages/deployer/src/types.ts
packages/deployer/src/utils/files.ts

Add only necessary data instead whole sections of `confgi.json` to avoid leaking secrets.
Resolve [AN-142](https://api3dao.atlassian.net/browse/AN-142)

Refactor `receipt.json` file generation

---

packages/protocol/contracts/admin/MetaAdminnable.sol
packages/protocol/contracts/admin/RankedAdminnable.sol
packages/protocol/contracts/rrp/AirnodeRrp.sol
packages/protocol/contracts/rrp/TemplateUtils.sol
packages/protocol/contracts/rrp/authorizers/Api3RequesterRrpAuthorizer.sol
packages/protocol/contracts/rrp/authorizers/SelfRequesterRrpAuthorizer.sol
packages/protocol/contracts/rrp/requesters/RrpBeaconServer.sol
packages/protocol/test/AirnodeRrp.sol.js
packages/protocol/test/TemplateUtils.sol.js
packages/protocol/test/authorizers/Api3RequesterRrpAuthorizer.sol.js
packages/protocol/test/authorizers/RequesterRrpAuthorizer.sol.js
packages/protocol/test/requesters/RrpBeaconServer.sol.js

The Following Issues are addressed in this pull request 
ARO-01
ARR-02
MAO-01
RBS-01
RBS-04
SRR-01
TUO-01

Certik revisions for Beta-Protocol

---

packages/node/src/evm/handlers/initialize-provider.test.ts
packages/node/src/evm/requests/api-calls.test.ts
packages/node/src/evm/requests/api-calls.ts
packages/node/src/evm/verification/api-call-verification.test.ts
packages/node/src/evm/verification/api-call-verification.ts
packages/node/src/handlers/start-coordinator.test.ts
packages/node/src/types.ts
packages/node/test/e2e/no-duplication.feature.ts
packages/node/test/e2e/requester-fulfill.feature.ts
packages/node/test/fixtures/evm/event-logs.ts
packages/node/test/fixtures/operation/requests.ts
packages/node/test/fixtures/requests/api-calls.ts

Calls to protocol where fine but there we were still calling it regular to template requests in node package.

AN-101: Replace regular requests with template requests

---

packages/node/src/evm/fulfillments/index.ts
packages/node/test/e2e/no-duplication.feature.ts
packages/node/test/e2e/request-status.feature.ts
packages/node/test/e2e/requester-fulfill.feature.ts
packages/node/test/e2e/withdrawals.feature.ts
packages/node/test/setup/e2e/index.ts
packages/node/test/setup/e2e/testing.ts
packages/node/test/setup/e2e/utils.ts

https://api3dao.atlassian.net/browse/AN-177

Fix e2e tests

---

packages/adapter/src/request-building/build-request.test.ts
packages/adapter/src/request-building/parameters.test.ts
packages/adapter/src/request-building/parameters.ts
packages/adapter/src/types.ts
packages/adapter/test/fixtures/options.ts
packages/node/src/handlers/call-api.test.ts
packages/node/src/handlers/call-api.ts

Same fix applied to master branch https://github.com/api3dao/airnode/pull/547

Fixes relay metadata parameters

---

packages/deployer/config/config.json.example
packages/node/__dev__/config.json.example
packages/node/src/coordinator/calls/aggregation.ts
packages/node/src/evm/handlers/initialize-provider.ts
packages/node/src/evm/verification/request-verification.test.ts
packages/node/src/evm/verification/request-verification.ts
packages/node/src/handlers/test-api.ts
packages/node/src/types.ts
packages/node/test/fixtures/config/config.ts

I'm not 100% if this refactor should be merged to master or beta-protocol-revision. @bbenligiray 
Docs update PR: https://github.com/api3dao/api3-docs/pull/220

AN-179: Rename request in config.triggers as rrp

---

packages/protocol/README.md
packages/protocol/contracts/adminnable/Adminnable.sol
packages/protocol/contracts/adminnable/SelfAdminnable.sol
packages/protocol/contracts/adminnable/Whitelister.sol
packages/protocol/contracts/rrp/AirnodeRrp.sol
packages/protocol/contracts/rrp/AuthorizationUtils.sol
packages/protocol/contracts/rrp/TemplateUtils.sol
packages/protocol/contracts/rrp/WithdrawalUtils.sol
packages/protocol/contracts/rrp/authorizers/RequesterRrpAuthorizer.sol
packages/protocol/contracts/rrp/requesters/RrpBeaconServer.sol
packages/protocol/contracts/rrp/requesters/interfaces/IRrpBeaconServer.sol
packages/protocol/contracts/rrp/requesters/mock/MockRrpRequester.sol
packages/protocol/test/rrp/AirnodeRrp.sol.js
packages/protocol/test/rrp/WithdrawalUtils.sol.js
packages/protocol/test/rrp/authorizers/AirnodeRequesterRrpAuthorizer.sol.js
packages/protocol/test/rrp/authorizers/DaoRequesterRrpAuthorizer.sol.js
packages/protocol/test/rrp/authorizers/RequesterRrpAuthorizer.sol.js
packages/protocol/test/rrp/requesters/RrpBeaconServer.sol.js

Rebased `beta-protocol` on top of master and this branch is ahead by 7 commits.
I'm assuming that Certik will no longer be using this branch or we will create a new one out of master if they do another follow up review.

Merge beta-protocol branch to master

---

packages/examples/aws.example.env
packages/examples/scripts/create-aws-secrets.ts

Fixes Airnode removal from AWS issue.

Fix AWS credentials env variable name

---

packages/admin/src/cli.ts
packages/admin/test/e2e/__snapshots__/cli.feature.ts.snap
packages/admin/test/e2e/cli.feature.ts
packages/deployer/package.json
packages/deployer/src/cli/index.ts
yarn.lock

Issue [AN-228](https://api3dao.atlassian.net/browse/AN-228)

Fix long arguments casing for CLIs 

---

packages/examples/README.md
packages/node/docker/README.md

https://api3dao.atlassian.net/browse/AN-251

Document how to run Airnode with local blockchain

---

package.json
packages/examples/dist/scripts/run-airnode-locally.js
packages/examples/scripts/run-airnode-locally.ts
packages/node/docker/README.md

https://api3dao.atlassian.net/browse/AN-268

Update airnode client image docs

---

.changeset/fifty-crabs-roll.md

This marks the changelog base and prepares all packages for version 0.2
See: https://api3dao.atlassian.net/wiki/spaces/AIRNODE/pages/35717121/Git+versioning+development+flow#%5BinlineExtension%5DInclude-all-packages-in-release for more information.

Add changeset for version 0.2

---

.changeset/olive-trains-thank.md
docker/Dockerfile
packages/airnode-deployer/docker/Dockerfile
packages/airnode-deployer/package.json
packages/airnode-node/docker/Dockerfile

Related to https://api3workspace.slack.com/archives/C02AYRX8D89/p1635787054053400

Fix missing dependencies in Docker image builds

---

.changeset/unlucky-beers-wonder.md
docker/Dockerfile
packages/airnode-adapter/contracts/TestDecoder.sol
packages/airnode-adapter/e2e/index.ts
packages/airnode-adapter/src/constants.ts
packages/airnode-adapter/src/response-processing/array-type.ts
packages/airnode-adapter/src/response-processing/casting.ts
packages/airnode-adapter/src/response-processing/encoding.ts
packages/airnode-adapter/src/response-processing/extraction.test.ts
packages/airnode-adapter/src/response-processing/extraction.ts
packages/airnode-adapter/src/types.ts
packages/airnode-deployer/src/handlers/aws/index.ts
packages/airnode-node/package.json
packages/airnode-node/src/adapters/http/worker.test.ts
packages/airnode-node/src/adapters/http/worker.ts
packages/airnode-node/src/handlers/call-api.test.ts
packages/airnode-node/src/handlers/call-api.ts
packages/airnode-node/src/handlers/test-api.test.ts
packages/airnode-node/src/handlers/test-api.ts
packages/airnode-node/src/utils/promise-utils.ts
packages/airnode-node/src/workers/local-handlers.test.ts
packages/airnode-node/src/workers/local-handlers.ts
packages/airnode-node/test/e2e/test-api.feature.ts
yarn.lock

https://api3dao.atlassian.net/browse/AN-125
Docs 1: https://github.com/api3dao/api3-docs/pull/408
Docs 2: https://github.com/api3dao/api3-docs/pull/417
Closes https://github.com/api3dao/airnode/issues/516

Support multiple values for Airnode responses

---

packages/airnode-admin/src/cli.ts
packages/airnode-admin/test/e2e/cli.feature.ts
packages/airnode-deployer/src/handlers/aws/index.ts
packages/airnode-node/package.json

https://api3dao.atlassian.net/browse/AN-341

Improve admin CLI generate-mnemonic command output

---

.changeset/nervous-cups-float.md
packages/airnode-adapter/e2e/index.ts
packages/airnode-adapter/src/constants.ts
packages/airnode-adapter/src/response-processing/extraction.test.ts
packages/airnode-adapter/src/response-processing/extraction.ts
packages/airnode-adapter/src/types.ts

https://api3dao.atlassian.net/browse/AN-353
Docs: https://github.com/api3dao/api3-docs/pull/409

Implement reserved parameter escaping

---

.changeset/wet-baboons-walk.md
packages/airnode-adapter/contracts/TestDecoder.sol
packages/airnode-adapter/e2e/index.ts
packages/airnode-adapter/src/constants.ts
packages/airnode-adapter/src/response-processing/casting.test.ts
packages/airnode-adapter/src/response-processing/casting.ts
packages/airnode-adapter/src/response-processing/encoding.test.ts
packages/airnode-adapter/src/response-processing/encoding.ts
packages/airnode-adapter/src/response-processing/extraction.test.ts
packages/airnode-adapter/src/response-processing/extraction.ts

https://api3dao.atlassian.net/browse/AN-344
docs: https://github.com/api3dao/api3-docs/pull/413

Implement timestamp value for _type parameter

---

packages/airnode-abi/package.json
packages/airnode-adapter/package.json
packages/airnode-admin/package.json
packages/airnode-node/package.json
packages/airnode-protocol/package.json
packages/airnode-protocol/scripts/run-hardhat-tests.ts
yarn.lock

https://api3workspace.slack.com/archives/C02AYRX8D89/p1637152987184400

Improve unit test time

---

.changeset/tame-bugs-retire.md
packages/airnode-validator/templates/0.3/apiSpecifications.json
packages/airnode-validator/templates/0.3/config.json
packages/airnode-validator/templates/0.3/endpoints.json
packages/airnode-validator/templates/0.3/ois.json
packages/airnode-validator/templates/0.3/receipt.json

https://api3dao.atlassian.net/browse/AN-386

Validator security schemes

---

packages/airnode-adapter/src/constants.ts
packages/airnode-adapter/src/response-processing/extraction.test.ts
packages/airnode-adapter/src/response-processing/extraction.ts

https://api3dao.atlassian.net/browse/AN-367

Limit encoded response size

---

.changeset/many-cameras-wonder.md
packages/airnode-deployer/src/cli/commands.test.ts
packages/airnode-deployer/src/cli/commands.ts
packages/airnode-deployer/src/cli/index.ts
packages/airnode-deployer/src/utils/validation.ts
packages/airnode-examples/scripts/deploy-airnode.ts
packages/airnode-examples/scripts/remove-airnode.ts

https://api3dao.atlassian.net/browse/AN-375

Add skip-version-check option to deployer

---

.changeset/gentle-sloths-glow.md
packages/airnode-node/src/constants.test.ts
packages/airnode-node/src/constants.ts
packages/airnode-node/src/evm/handlers/fetch-pending-requests.test.ts
packages/airnode-node/src/evm/handlers/fetch-pending-requests.ts
packages/airnode-node/src/evm/requests/blocking.test.ts
packages/airnode-node/src/evm/requests/blocking.ts
packages/airnode-node/src/types.ts

https://api3dao.atlassian.net/browse/AN-396

Add sponsor wallet request limit

---

packages/airnode-node/src/coordinator/calls/coordinated-execution.test.ts
packages/airnode-node/src/coordinator/calls/coordinated-execution.ts
packages/airnode-node/src/coordinator/calls/disaggregation.ts
packages/airnode-node/src/evm/fulfillments/api-calls.test.ts
packages/airnode-node/src/evm/fulfillments/api-calls.ts
packages/airnode-node/src/handlers/call-api.test.ts
packages/airnode-node/src/handlers/call-api.ts
packages/airnode-node/src/types.ts
packages/airnode-node/test/fixtures/requests/api-calls.ts

Issue [AN-397](https://api3dao.atlassian.net/browse/AN-397)

Move response signing from `processTransactions` handler to `callApi`

---

.changeset/friendly-donkeys-sing.md
packages/airnode-deployer/config/config.json.example
packages/airnode-examples/integrations/authenticated-coinmarketcap/config.example.json
packages/airnode-examples/integrations/coingecko-testable/config.example.json
packages/airnode-examples/integrations/coingecko/config.example.json
packages/airnode-examples/integrations/config-utils.ts
packages/airnode-examples/integrations/weather-multi-value/config.example.json
packages/airnode-node/config/config.json.example
packages/airnode-validator/exampleSpecs/config.specs.json
packages/airnode-validator/templates/0.4/apiSpecifications.json
packages/airnode-validator/templates/0.4/config.json
packages/airnode-validator/templates/0.4/endpoints.json
packages/airnode-validator/templates/0.4/ois.json
packages/airnode-validator/templates/0.4/receipt.json
packages/airnode-validator/test/validatorTests/endpoints.json
packages/airnode-validator/test/validatorTests/minimal.json
packages/airnode-validator/test/validatorTests/multipleOIS.json
packages/airnode-validator/test/validatorTests/paths.json
packages/airnode-validator/test/validatorTests/security.json

- Initialise validator templates and examples for v0.4.0 to allow further development of the `config.json` specification.
- Relates to AN-444

Initialise validator templates and examples for v0.4.0

---

.changeset/silent-bulldogs-do.md
packages/airnode-deployer/src/handlers/aws/index.ts
packages/airnode-deployer/src/handlers/gcp/index.ts
packages/airnode-node/package.json
packages/airnode-node/src/adapters/http/worker.test.ts
packages/airnode-node/src/adapters/http/worker.ts
packages/airnode-node/src/coordinator/calls/aggregation.test.ts
packages/airnode-node/src/coordinator/calls/aggregation.ts
packages/airnode-node/src/coordinator/calls/coordinated-execution.test.ts
packages/airnode-node/src/coordinator/calls/coordinated-execution.ts
packages/airnode-node/src/coordinator/calls/disaggregation.test.ts
packages/airnode-node/src/coordinator/state.test.ts
packages/airnode-node/src/evm/handlers/initialize-provider.ts
packages/airnode-node/src/evm/requests/event-logs.test.ts
packages/airnode-node/src/evm/verification/api-call-verification.test.ts
packages/airnode-node/src/evm/verification/request-verification.ts
packages/airnode-node/src/handlers/call-api.test.ts
packages/airnode-node/src/handlers/call-api.ts
packages/airnode-node/src/handlers/test-api.test.ts
packages/airnode-node/src/handlers/test-api.ts
packages/airnode-node/src/types.ts
packages/airnode-node/src/workers/local-handlers.test.ts
packages/airnode-node/src/workers/local-handlers.ts
packages/airnode-node/test/e2e/test-api.feature.ts
packages/airnode-node/test/fixtures/aggregated-api-call.ts

https://api3dao.atlassian.net/browse/AN-394

Move sponsor wallet check to callApi

---

packages/airnode-validator/README.md

https://github.com/api3dao/airnode/pull/753#discussion_r777411573

Remove redundant commands

---

.changeset/green-dryers-play.md
packages/airnode-validator/src/validator.test.ts
packages/airnode-validator/templates/1.0/endpoints.json

Fix validator template operationParameter regex

---

.changeset/rude-donuts-impress.md
packages/airnode-admin/src/cli.ts
packages/airnode-admin/src/evm.ts
packages/airnode-admin/src/implementation.ts
packages/airnode-admin/src/sdk.ts
packages/airnode-admin/test/e2e/__snapshots__/cli.feature.ts.snap
packages/airnode-admin/test/e2e/cli.feature.ts
packages/airnode-admin/test/e2e/sdk.feature.ts
packages/airnode-examples/README.md
packages/airnode-examples/package.json
packages/airnode-examples/scripts/make-request.ts
packages/airnode-examples/scripts/make-withdrawal-request.ts
packages/airnode-examples/scripts/sponsor-requester.ts
packages/airnode-examples/src/utils.test.ts
packages/airnode-examples/src/utils.ts

https://api3dao.atlassian.net/browse/AN-410

Support withdrawals in Airnode examples, add "derive-airnode-address" command to admin CLI

---

packages/airnode-node/src/evm/fulfillments/index.test.ts
packages/airnode-node/src/evm/fulfillments/index.ts
packages/airnode-node/src/evm/handlers/process-transactions.test.ts
packages/airnode-node/src/evm/handlers/process-transactions.ts
packages/airnode-node/src/evm/workers.test.ts
packages/airnode-node/src/evm/workers.ts
packages/airnode-node/src/handlers/process-transactions.test.ts
packages/airnode-node/src/handlers/process-transactions.ts
packages/airnode-node/src/handlers/start-coordinator.ts
packages/airnode-node/src/providers/actions.test.ts
packages/airnode-node/src/providers/actions.ts
packages/airnode-node/src/providers/state.test.ts
packages/airnode-node/src/providers/state.ts
packages/airnode-node/src/providers/worker.ts
packages/airnode-node/src/requests/grouping.ts
packages/airnode-node/src/requests/nonces.test.ts
packages/airnode-node/src/requests/nonces.ts
packages/airnode-node/src/types.ts
packages/airnode-node/src/workers/local-handlers.test.ts
packages/airnode-node/src/workers/local-handlers.ts
packages/airnode-node/test/fixtures/provider-states/evm.ts

[Issue AN-398](https://api3dao.atlassian.net/browse/AN-398)

Invoke process transactions per sponsor wallet

---

.changeset/twenty-guests-occur.md
packages/airnode-adapter/src/request-building/authentication.test.ts
packages/airnode-adapter/src/request-building/authentication.ts
packages/airnode-adapter/test/fixtures/ois.ts
packages/airnode-adapter/test/fixtures/security.ts
packages/airnode-deployer/test/fixtures/config/ois.ts
packages/airnode-node/test/fixtures/config/ois.ts
packages/airnode-ois/src/types.ts

https://api3dao.atlassian.net/browse/AN-496

Implement sponsorAddress and sponsorWalletAddress relay security schemes

---

.changeset/plenty-taxis-try.md
packages/airnode-deployer/src/handlers/gcp/index.ts
packages/airnode-deployer/terraform/airnode/aws/main.tf
packages/airnode-deployer/terraform/airnode/gcp/main.tf
packages/airnode-deployer/terraform/airnode/gcp/modules/apigateway/main.tf
packages/airnode-deployer/terraform/airnode/gcp/modules/apigateway/outputs.tf
packages/airnode-deployer/terraform/airnode/gcp/modules/apigateway/variables.tf
packages/airnode-deployer/terraform/airnode/gcp/modules/function/main.tf
packages/airnode-deployer/terraform/airnode/gcp/modules/function/variables.tf
packages/airnode-deployer/terraform/airnode/gcp/outputs.tf
packages/airnode-deployer/terraform/airnode/gcp/providers.tf
packages/airnode-deployer/terraform/airnode/gcp/templates/apigateway.yaml.tpl
packages/airnode-deployer/terraform/state/gcp/providers.tf

[Issue AN-308](https://api3dao.atlassian.net/browse/AN-308)

Add HTTP gateway support for GCP

---

.changeset/loud-bags-repeat.md
packages/airnode-deployer/src/infrastructure/aws.ts
packages/airnode-deployer/src/infrastructure/index.ts
packages/airnode-deployer/terraform/state/aws/main.tf

[Issue AN-499](https://api3dao.atlassian.net/browse/AN-499)

Remove DynamoDB locks from AWS Terraform recipes

---

packages/airnode-node/src/evm/fulfillments/api-calls.test.ts

[AN-523](https://api3dao.atlassian.net/browse/AN-523)

Add unit test for error message trimming

---

.changeset/unlucky-tips-allow.md
packages/airnode-deployer/package.json
packages/airnode-deployer/src/entrypoint.ts
packages/airnode-deployer/src/handlers/aws/index.ts
packages/airnode-deployer/src/handlers/gcp/index.ts
packages/airnode-deployer/terraform/airnode/aws/main.tf
packages/airnode-deployer/terraform/airnode/gcp/main.tf
packages/airnode-node/src/adapters/http/worker.test.ts
packages/airnode-node/src/adapters/http/worker.ts
packages/airnode-node/src/constants.test.ts
packages/airnode-node/src/constants.ts
packages/airnode-node/src/evm/workers.test.ts
packages/airnode-node/src/evm/workers.ts
packages/airnode-node/src/providers/actions.ts
packages/airnode-node/src/providers/worker.test.ts
packages/airnode-node/src/types.ts
packages/airnode-node/src/workers/cloud-platforms/aws.test.ts
packages/airnode-node/src/workers/cloud-platforms/aws.ts
packages/airnode-node/src/workers/cloud-platforms/gcp.test.ts
packages/airnode-node/src/workers/cloud-platforms/gcp.ts
packages/airnode-node/src/workers/index.test.ts
packages/airnode-node/src/workers/index.ts
packages/airnode-node/src/workers/local-handlers.test.ts
packages/airnode-node/src/workers/local-handlers.ts
yarn.lock

[Issue AN-514](https://api3dao.atlassian.net/browse/AN-514)

Merge serverless handlers to share the concurrency reservation

---

packages/airnode-examples/README.md

https://api3dao.atlassian.net/browse/AN-511
Feel free to close if not applicable.

Clarify the need to build airnode-examples

---

.changeset/rude-carrots-listen.md
packages/airnode-node/src/evm/handlers/initialize-provider.test.ts
packages/airnode-node/src/evm/requests/event-logs.test.ts
packages/airnode-node/src/evm/requests/event-logs.ts

https://api3dao.atlassian.net/browse/AN-535

Remove retries and timeout for getLogs

---

.changeset/gentle-elephants-tan.md
packages/airnode-deployer/config/config.json.example
packages/airnode-deployer/src/cli/__tests__/commands.test.ts
packages/airnode-deployer/src/cli/commands.ts
packages/airnode-deployer/src/infrastructure/index.ts
packages/airnode-deployer/src/utils/files.ts
packages/airnode-deployer/terraform/airnode/aws/main.tf
packages/airnode-deployer/terraform/airnode/aws/variables.tf
packages/airnode-deployer/terraform/airnode/gcp/main.tf
packages/airnode-deployer/terraform/airnode/gcp/variables.tf
packages/airnode-examples/integrations/config-utils.ts
packages/airnode-node/src/adapters/http/worker.test.ts
packages/airnode-node/src/evm/workers.test.ts
packages/airnode-node/src/providers/worker.test.ts
packages/airnode-node/src/types.ts
packages/airnode-node/src/workers/cloud-platforms/aws.test.ts
packages/airnode-node/src/workers/cloud-platforms/gcp.test.ts
packages/airnode-node/src/workers/index.test.ts
packages/airnode-validator/exampleSpecs/secrets.config.json
packages/airnode-validator/templates/0.5/config.json
packages/airnode-validator/templates/0.5/receipt.json
packages/airnode-validator/test/validatorTests/endpoints.json
packages/airnode-validator/test/validatorTests/minimal.json
packages/airnode-validator/test/validatorTests/multipleOIS.json
packages/airnode-validator/test/validatorTests/paths.json
packages/airnode-validator/test/validatorTests/security.json

[Issue AN-515](https://api3dao.atlassian.net/browse/AN-515)

Add concurrency reservation for serverless functions

---

.changeset/eight-roses-shave.md
packages/airnode-node/src/reporting/heartbeat.test.ts
packages/airnode-node/src/reporting/heartbeat.ts

Cherry-pick of https://github.com/api3dao/airnode/pull/839 for v0.4

Fix heartbeat API key location & name (v0.4)

---

.changeset/great-rivers-rest.md
packages/airnode-admin/src/cli.ts
packages/airnode-admin/test/e2e/cli.feature.ts

Jira: [AN419](https://api3dao.atlassian.net/jira/software/projects/AN/boards/18?selectedIssue=AN-419)

AN419: Display airnode address and xpub with generate-mnemonic

---

.changeset/long-guests-taste.md
packages/airnode-admin/src/cli-examples.ts
packages/airnode-admin/src/cli.ts
packages/airnode-admin/test/e2e/__snapshots__/cli.feature.ts.snap
packages/airnode-admin/test/e2e/cli.feature.ts
packages/airnode-deployer/README.md
packages/airnode-deployer/src/cli/cli-examples.ts
packages/airnode-deployer/src/cli/index.ts

Left out the validator CLI as it may change, but can be added as needed.

Add CLI examples to admin and deployer packages

---

.changeset/few-eels-tan.md
.changeset/fifty-doors-give.md
packages/airnode-deployer/config/config.example.json
packages/airnode-examples/integrations/authenticated-coinmarketcap/config.example.json
packages/airnode-examples/integrations/authenticated-coinmarketcap/create-config.ts
packages/airnode-examples/integrations/coingecko-testable/config.example.json
packages/airnode-examples/integrations/coingecko-testable/create-config.ts
packages/airnode-examples/integrations/coingecko/config.example.json
packages/airnode-examples/integrations/coingecko/create-config.ts
packages/airnode-examples/integrations/relay-security-schemes/config.example.json
packages/airnode-examples/integrations/relay-security-schemes/create-config.ts
packages/airnode-examples/integrations/weather-multi-value/config.example.json
packages/airnode-examples/integrations/weather-multi-value/create-config.ts
packages/airnode-node/config/config.example.json
packages/airnode-node/src/config/types.ts
packages/airnode-node/src/evm/gas-prices.test.ts
packages/airnode-node/src/evm/gas-prices.ts
packages/airnode-node/src/providers/actions.test.ts
packages/airnode-node/src/providers/state.test.ts
packages/airnode-node/test/setup/e2e/utils.ts
packages/airnode-validator/exampleSpecs/config.specs.json
packages/airnode-validator/exampleSpecs/interpolated-config.specs.json
packages/airnode-validator/exampleSpecs/secrets.config.json
packages/airnode-validator/src/v2/config/config.ts
packages/airnode-validator/templates/0.4/config.json
packages/airnode-validator/templates/0.5/config.json
packages/airnode-validator/test/validatorTests/multipleOIS.json

This revert _should_ fix a bug introduced by an eip1559-related type change, originally merged from PR #890

Revert Merge in Change EIP1559 config value string type switch

---

packages/airnode-protocol-v1/contracts/monetization/RequesterAuthorizerWhitelisterWithToken.sol
packages/airnode-protocol-v1/contracts/monetization/RequesterAuthorizerWhitelisterWithTokenDeposit.sol
packages/airnode-protocol-v1/contracts/monetization/RequesterAuthorizerWhitelisterWithTokenPayment.sol

Using SafeERC20 in case the token in question doesn't conform to ERC20 exactly

Use the SafeERC20 library

---

.changeset/thin-mails-sip.md
packages/airnode-node/src/reporting/heartbeat.test.ts
packages/airnode-node/src/reporting/heartbeat.ts

[Issue AN-600](https://api3dao.atlassian.net/browse/AN-600)
Forgot to add this during the HTTP Signed Data Gateway implementation. Also, I fixed the bug that was causing not sending the gateway URL even before :sweat_smile:

Send HTTP Signed Data Gateway URL within the heartbeat

---

.changeset/fast-fireants-eat.md
packages/airnode-deployer/terraform/airnode/gcp/main.tf

https://api3workspace.slack.com/archives/C02R79STBRA/p1647438502346109

Fix handler naming in GCP Terraform recipe

---

.changeset/ten-rabbits-tell.md
packages/airnode-deployer/src/cli/__tests__/commands.test.ts
packages/airnode-deployer/src/cli/commands.ts
packages/airnode-deployer/src/types.ts
packages/airnode-deployer/src/utils/files.ts

[AN-633](https://api3dao.atlassian.net/browse/AN-633).
I deployed and `receipt.json` had the correct ISO timestamp:
```json
"timestamp": "2022-03-26T02:37:55.506Z"
```

Add ISO formatted timestamp to receipt.json

---

.changeset/eight-gifts-whisper.md
packages/airnode-deployer/src/handlers/aws/index.ts
packages/airnode-deployer/src/handlers/gcp/index.ts
packages/airnode-examples/integrations/coingecko-signed-data/README.md

https://api3dao.atlassian.net/browse/AN-558
Docs: https://github.com/api3dao/api3-docs/pull/684

Fix signed data Airnode example

---

.changeset/slimy-adults-provide.md
packages/airnode-node/src/handlers/start-coordinator.ts

[AN-643](https://api3dao.atlassian.net/browse/AN-643)

Fix misleading log in initiateTransactions

---

.changeset/silver-terms-prove.md
packages/airnode-node/src/evm/handlers/initialize-provider.ts
packages/airnode-node/src/evm/transaction-counts.test.ts
packages/airnode-node/src/evm/transaction-counts.ts

This adds `minConfirmations` to transaction count fetching.

Add minConfirmations to getWalletTransactionCount

---

.changeset/sharp-otters-tease.md
packages/airnode-deployer/package.json
packages/airnode-deployer/src/cli/commands.ts
packages/airnode-deployer/src/cli/index.ts
packages/airnode-deployer/src/infrastructure/index.ts
packages/airnode-deployer/src/utils/evm.ts
packages/airnode-deployer/src/utils/files.ts
packages/airnode-deployer/src/utils/infrastructure.ts
packages/airnode-deployer/terraform/airnode/gcp/outputs.tf
packages/airnode-examples/integrations/coingecko-signed-data/README.md

Applies https://github.com/api3dao/airnode/pull/1022 to the 0.5 release.

[v0.5]: Fix GCP signed data gateway receipt URL, let deployer fail with non zero status code

---

.changeset/rude-clouds-draw.md
package.json
packages/airnode-deployer/terraform/airnode/gcp/main.tf

Applies https://github.com/api3dao/airnode/pull/1044 to the 0.5 release.

[v0.5]: Fix condition for enabling GCP API gateway service

---

.changeset/stale-beers-tickle.md
packages/airnode-node/src/api/index.ts
packages/airnode-node/src/evm/templates/template-verification.test.ts
packages/airnode-node/src/evm/templates/template-verification.ts
packages/airnode-node/src/handlers/process-http-signed-data-request.test.ts
packages/airnode-node/src/handlers/process-http-signed-data-request.ts

Apply changes from #1037 to `v0.6`

[v0.6] Fix template ID derivation for signed data gateway

---

.changeset/stale-beers-tickle.md
packages/airnode-node/src/api/index.ts
packages/airnode-node/src/evm/templates/template-verification.test.ts
packages/airnode-node/src/evm/templates/template-verification.ts
packages/airnode-node/src/handlers/process-http-signed-data-request.test.ts
packages/airnode-node/src/handlers/process-http-signed-data-request.ts

Apply changes from https://github.com/api3dao/airnode/pull/1037 to v0.5

[v0.5] Fix template ID derivation for signed data gateway

---

.changeset/soft-bananas-check.md
packages/airnode-deployer/src/cli/commands.ts
packages/airnode-examples/integrations/authenticated-coinmarketcap/config.example.json
packages/airnode-examples/integrations/authenticated-coinmarketcap/create-config.ts
packages/airnode-examples/integrations/coingecko-signed-data/config.example.json
packages/airnode-examples/integrations/coingecko-signed-data/create-config.ts
packages/airnode-examples/integrations/coingecko-testable/config.example.json
packages/airnode-examples/integrations/coingecko-testable/create-config.ts
packages/airnode-examples/integrations/coingecko/config.example.json
packages/airnode-examples/integrations/coingecko/create-config.ts
packages/airnode-examples/integrations/failing-example/config.example.json
packages/airnode-examples/integrations/failing-example/create-config.ts
packages/airnode-examples/integrations/relay-security-schemes/config.example.json
packages/airnode-examples/integrations/relay-security-schemes/create-config.ts
packages/airnode-examples/integrations/weather-multi-value/config.example.json
packages/airnode-examples/integrations/weather-multi-value/create-config.ts
packages/airnode-node/src/config/types.ts
packages/airnode-validator/exampleSpecs/config.specs.json
packages/airnode-validator/exampleSpecs/interpolated-config.specs.json
packages/airnode-validator/src/config/config.ts

https://api3dao.atlassian.net/browse/AN-556

Remove skipValidation parameter

---

.changeset/cold-rocks-sort.md
packages/airnode-deployer/test/fixtures/invalid-receipt.json
packages/airnode-validator/package.json
packages/airnode-validator/src/api/api.ts
packages/airnode-validator/src/config/config.ts
packages/airnode-validator/src/receipt/receipt.test.ts
packages/airnode-validator/src/receipt/receipt.ts
packages/airnode-validator/test/fixtures/receipt.valid.json

[AN-708](https://api3dao.atlassian.net/browse/AN-708)

Refine receipt.json validation

---

docker/Dockerfile

Regarding https://api3workspace.slack.com/archives/C02AYRX8D89/p1653545236645239

Fix lerna version in Docker build

---

.changeset/stupid-swans-ring.md
packages/airnode-examples/integrations/authenticated-coinmarketcap/config.example.json
packages/airnode-examples/integrations/authenticated-coinmarketcap/create-config.ts
packages/airnode-node/config/config.example.json
packages/airnode-node/test/fixtures/config/ois.ts
packages/airnode-validator/src/ois/ois.test.ts
packages/airnode-validator/src/ois/ois.ts

https://api3dao.atlassian.net/browse/AN-613

Validate API specification parameters

---

.changeset/real-bugs-matter.md
packages/airnode-adapter/src/request-building/parameters.ts
packages/airnode-validator/src/ois/ois.test.ts
packages/airnode-validator/src/ois/ois.ts

https://api3dao.atlassian.net/browse/AN-753

Allow parameters with same name, but different location

---

.changeset/ninety-foxes-film.md
packages/airnode-validator/package.json

The addition mirrors other `airnode-` packages

Add jest to airnode-validator devDependencies

---

.changeset/eighty-crabs-press.md
packages/airnode-node/src/evm/handlers/initialize-provider.ts
packages/airnode-node/src/evm/verification/request-verification.test.ts
packages/airnode-node/src/evm/verification/request-verification.ts
packages/airnode-node/src/handlers/process-http-request.test.ts
packages/airnode-node/src/handlers/process-http-request.ts
packages/airnode-node/src/handlers/process-http-signed-data-request.test.ts
packages/airnode-node/src/handlers/process-http-signed-data-request.ts
packages/airnode-validator/src/config/config.test.ts
packages/airnode-validator/src/config/config.ts

[AN-617](https://api3dao.atlassian.net/browse/AN-617)

Add validation checks for references within triggers

---

.changeset/dull-moose-cover.md
packages/airnode-validator/src/config/config.test.ts
packages/airnode-validator/src/config/config.ts
packages/airnode-validator/src/ois/ois.test.ts
packages/airnode-validator/src/ois/ois.ts
packages/airnode-validator/src/receipt/receipt.test.ts
packages/airnode-validator/src/types.ts

[AN-619](https://api3dao.atlassian.net/browse/AN-619)

Enable zod strict mode

---

.changeset/silver-icons-repair.md
packages/airnode-deployer/config/config.example.json
packages/airnode-examples/integrations/authenticated-coinmarketcap/config.example.json
packages/airnode-examples/integrations/authenticated-coinmarketcap/create-config.ts
packages/airnode-examples/integrations/coingecko-post-processing/config.example.json
packages/airnode-examples/integrations/coingecko-post-processing/create-config.ts
packages/airnode-examples/integrations/coingecko-pre-processing/config.example.json
packages/airnode-examples/integrations/coingecko-pre-processing/create-config.ts
packages/airnode-examples/integrations/coingecko/config.example.json
packages/airnode-examples/integrations/coingecko/create-config.ts
packages/airnode-examples/integrations/failing-example/config.example.json
packages/airnode-examples/integrations/failing-example/create-config.ts
packages/airnode-examples/integrations/relay-security-schemes/config.example.json
packages/airnode-examples/integrations/relay-security-schemes/create-config.ts
packages/airnode-examples/integrations/weather-multi-value/config.example.json
packages/airnode-examples/integrations/weather-multi-value/create-config.ts
packages/airnode-node/src/reporting/heartbeat.test.ts
packages/airnode-node/src/reporting/heartbeat.ts
packages/airnode-validator/src/config/config.test.ts
packages/airnode-validator/src/config/config.ts
packages/airnode-validator/test/fixtures/config.valid.json
packages/airnode-validator/test/fixtures/interpolated-config.valid.json

[AN-764](https://api3dao.atlassian.net/browse/AN-764) plus other small refactors (see commit messages).

Fix check for AWS API key uniqueness

---

.changeset/wise-pots-wait.md
packages/airnode-deployer/terraform/airnode/aws/main.tf
packages/airnode-deployer/terraform/airnode/gcp/main.tf

https://api3workspace.slack.com/archives/C02AYRX8D89/p1654257231432529?thread_ts=1654185413.354569&cid=C02AYRX8D89

Adjust memory allocation for gateway serverless functions

---

.changeset/wise-lamps-divide.md
packages/airnode-node/src/coordinator/calls/chain-limits.test.ts
packages/airnode-node/src/providers/actions.test.ts
packages/airnode-utilities/src/evm/gas-prices/gas-prices.test.ts
packages/airnode-utilities/src/evm/gas-prices/gas-prices.ts
packages/airnode-validator/src/config/config.test.ts
packages/airnode-validator/src/config/config.ts
packages/airnode-validator/src/ois/ois.test.ts
packages/airnode-validator/src/ois/ois.ts

https://api3dao.atlassian.net/browse/AN-616
Review commit by commit.

Legacy validator rules

---

.changeset/gorgeous-lions-agree.md
packages/airnode-adapter/src/request-building/parameters.ts
packages/airnode-admin/src/implementation.ts
packages/airnode-node/src/api/index.test.ts
packages/airnode-node/src/api/index.ts
packages/airnode-node/src/validation.ts
packages/airnode-node/test/e2e/signed-data.feature.ts
packages/airnode-utilities/src/constants.ts
packages/airnode-utilities/src/evm/gas-prices/gas-prices.test.ts
packages/airnode-utilities/src/evm/gas-prices/gas-prices.ts
packages/airnode-utilities/src/evm/gas-prices/types.ts
packages/airnode-validator/src/api/api.ts
packages/airnode-validator/src/config/config.ts
packages/airnode-validator/src/ois/ois.test.ts
packages/airnode-validator/src/ois/ois.ts
packages/airnode-validator/src/receipt/receipt.ts

https://api3dao.atlassian.net/browse/AN-770
Review commit by commit.
While implementing this change I realized that the validation of the parameters could be more thorough and I've implemented it as the last commit.

Strenghten schema

---

.changeset/hot-countries-switch.md
packages/airnode-validator/src/config/config.test.ts
packages/airnode-validator/src/config/config.ts
packages/airnode-validator/src/ois/ois.ts

[AN-405](https://api3dao.atlassian.net/browse/AN-405)

Reject configuration with both relay metadata security schemes and gateways

---

.changeset/unlucky-pumpkins-mix.md
packages/airnode-examples/integrations/coingecko-post-processing/config.example.json
packages/airnode-examples/integrations/coingecko-post-processing/create-config.ts
packages/airnode-examples/integrations/coingecko-pre-processing/config.example.json
packages/airnode-examples/integrations/coingecko-pre-processing/create-config.ts
packages/airnode-node/package.json
packages/airnode-node/src/api/unsafe-evaluate.test.ts
packages/airnode-node/src/api/unsafe-evaluate.ts
packages/airnode-node/src/api/vm-timers.ts
packages/airnode-validator/src/api/api.test.ts
packages/airnode-validator/src/api/api.ts

https://api3dao.atlassian.net/browse/AN-750

Allow setTimeout/setInterval and escaping interpolation in processing snippets

---

.changeset/unlucky-jeans-agree.md
packages/airnode-node/src/handlers/start-coordinator.ts
packages/airnode-node/src/providers/actions.test.ts
packages/airnode-node/src/providers/actions.ts

[AN-775](https://api3dao.atlassian.net/browse/AN-775)

Allow empty `chains` array in the config

---

.changeset/long-pens-collect.md
packages/airnode-deployer/src/cli/index.ts

[AN-774](https://api3dao.atlassian.net/browse/AN-774)

Remove deployer version from deployer output

---

.changeset/late-pans-occur.md
packages/airnode-examples/integrations/coingecko-signed-data/README.md
packages/airnode-examples/src/scripts/choose-integration.ts

Improve coingecko-signed-data examples integration

---

.changeset/nice-dolls-brush.md
packages/airnode-node/src/config/index.ts
packages/airnode-utilities/src/evm/gas-prices/types.ts
packages/airnode-validator/src/config/config.test.ts

Minor follow-up to d90a4d70f90c9d6798cac71da2cd8cdf20190b67

Make "unit" required for priorityFee

---

.changeset/shy-weeks-provide.md
packages/airnode-adapter/src/constants.ts
packages/airnode-adapter/src/response-processing/extraction.test.ts

https://api3dao.atlassian.net/browse/AN-784

Update max fulfillment size

---

.changeset/thirty-ads-wonder.md
packages/airnode-validator/src/api/api.test.ts
packages/airnode-validator/src/api/api.ts

Support multiline secrets in validator

---

.changeset/fast-moles-swim.md
packages/airnode-deployer/src/cli/commands.test.ts
packages/airnode-deployer/src/cli/commands.ts
packages/airnode-deployer/src/utils/files.ts
packages/airnode-deployer/test/fixtures/invalid-receipt.json
packages/airnode-examples/integrations/coingecko-signed-data/README.md
packages/airnode-examples/integrations/coingecko-testable/README.md
packages/airnode-validator/src/receipt/receipt.ts
packages/airnode-validator/test/fixtures/receipt.valid.json

Remove gateway URLs from receipt.json

---

.changeset/early-penguins-unite.md
packages/airnode-admin/src/mnemonic.test.ts
packages/airnode-admin/src/mnemonic.ts
packages/airnode-admin/test/e2e/cli.feature.ts

Close #1192 
Followup to #1262

Improve mnemonic visibility in `generate-mnemonic` command

---

.changeset/blue-gifts-rule.md
packages/airnode-admin/src/implementation.ts
packages/airnode-node/src/evm/wallet.ts
packages/airnode-operation/src/evm/utils.ts
packages/airnode-protocol/src/index.ts
packages/airnode-protocol/test/utils.js

Closes https://github.com/api3dao/airnode/issues/1195

Define protocol indices in airnode-protocol

---

.changeset/yellow-bags-hang.md
packages/airnode-deployer/terraform/airnode/gcp/main.tf

Fix GCP gateway URLs in heartbeat payload

---

.changeset/breezy-bats-attack.md
packages/airnode-deployer/src/cli/commands.test.ts
packages/airnode-deployer/src/cli/commands.ts
packages/airnode-deployer/src/cli/index.ts
packages/airnode-deployer/src/utils/infrastructure.ts

Closes https://github.com/api3dao/airnode/issues/1188

Auto remove deployment

---

.changeset/wild-schools-collect.md
packages/airnode-deployer/src/cli/index.ts

Fix for https://github.com/api3dao/airnode/issues/1188
Michal pointed out an inconsistency I introduced when changing the logic of the command in https://github.com/api3dao/api3-docs/pull/860#discussion_r914478132

Fix deployer "auto-remove" parameter description

---

renovate.json

This will automatically merge the PR once there was approval from someone and the required status checks pass: https://docs.renovatebot.com/key-concepts/automerge/#required-pull-request-reviews

Enable renovate automerge

---

.changeset/cuddly-teachers-dream.md
packages/airnode-deployer/docker/entrypoint.sh
packages/airnode-examples/README.md
packages/airnode-examples/src/scripts/create-aws-secrets.ts
packages/airnode-examples/src/scripts/deploy-airnode.ts
packages/airnode-examples/src/scripts/remove-airnode.ts
packages/airnode-examples/src/utils.ts

Mount aws.env to deployer docker image and export with entrypoint

---

.changeset/chilled-cycles-think.md
.github/workflows/build-test.yml
.github/workflows/mlc_config.json

Fixes grep partial matches with `latestVersion` and `latestVersions` in the check documentatiom job.

Fix check documentation latest path update loop

---

.changeset/olive-grapes-fix.md
packages/airnode-deployer/src/handlers/aws/index.ts
packages/airnode-deployer/src/handlers/gcp/index.ts
packages/airnode-node/src/adapters/http/worker.test.ts
packages/airnode-node/src/workers/local-handlers.ts
packages/airnode-node/test/fixtures/log-options.ts
packages/airnode-utilities/src/logging/logging.test.ts
packages/airnode-utilities/src/logging/logging.ts
packages/airnode-utilities/src/logging/types.ts

Closes https://github.com/api3dao/airnode/issues/1181
I also noticed that we stopped including some metadata in the logger in https://github.com/api3dao/airnode/pull/1341 so I added it back.
TODO:

Merge meta and additional fields of logger

---

.changeset/shy-apples-wash.md
packages/airnode-deployer/terraform/airnode/gcp/main.tf

Closes https://github.com/api3dao/airnode/issues/1358.
Cherry pick of https://github.com/api3dao/airnode/pull/1349

[v0.6] Turn off GCP service disabling

---

.changeset/thin-oranges-sin.md
packages/airnode-deployer/terraform/airnode/gcp/main.tf

Closes https://github.com/api3dao/airnode/issues/1359
Cherry pick of https://github.com/api3dao/airnode/pull/1349

[v0.7] Turn off GCP service disabling

---

.changeset/thirty-seals-hear.md
packages/airnode-examples/README.md
packages/airnode-examples/src/evm.ts
packages/airnode-examples/src/scripts/choose-integration.ts
packages/airnode-examples/src/utils.test.ts
packages/airnode-examples/src/utils.ts

Default to deployed AirnodeRrpV0 in airnode-examples

---

.changeset/real-rice-train.md
packages/airnode-node/src/api/index.ts
packages/airnode-node/src/index.ts

Exports functions under /api directory on airnode-node package

---

.changeset/lemon-schools-build.md
packages/airnode-examples/CHANGELOG.md

Fixes an outdated github account causing CI link checker to fail.

Fix outdated github account

---

.changeset/small-trains-hide.md
packages/airnode-examples/integrations/config-utils.ts

Disable concurrency in airnode-examples

---

packages/airnode-deployer/src/infrastructure/aws.test.ts
packages/airnode-deployer/src/infrastructure/aws.ts
packages/airnode-deployer/src/infrastructure/gcp.test.ts
packages/airnode-deployer/src/infrastructure/gcp.ts
packages/airnode-deployer/src/infrastructure/index.test.ts
packages/airnode-deployer/src/infrastructure/index.ts
packages/airnode-deployer/src/utils/infrastructure.ts
packages/airnode-deployer/test/fixtures/index.ts

Use the region of the first Airnode deployment for the bucket location

---

.changeset/five-rivers-brush.md
packages/airnode-deployer/terraform/aws/modules/function/main.tf
packages/airnode-deployer/terraform/gcp/modules/function/main.tf

Backport of https://github.com/api3dao/airnode/pull/1513 to v0.9

[v0.9] Fix handling of quotation marks in secrets

---

.changeset/itchy-kings-pay.md
packages/airnode-deployer/src/infrastructure/index.test.ts
packages/airnode-deployer/src/infrastructure/index.ts

Fix #1546
Better error handling will be introduced in https://github.com/api3dao/airnode/issues/1449

Fix deployment ID generation

---

.changeset/strong-llamas-laugh.md
packages/airnode-utilities/src/logging/logging.ts

Closes https://github.com/api3dao/airnode/issues/1583
Cherry pick of https://github.com/api3dao/airnode/pull/1564/commits/3034ad0b10e7cd9c464132bdcce50743029a31f5

[v0.9] Fix undefined error property in json logging

---

.changeset/kind-hairs-marry.md
.prettierignore
packages/airnode-protocol/.prettierignore
packages/airnode-protocol/contracts/rrp/interfaces/ITemplateUtilsV0.sol
packages/airnode-protocol/credentials.example.json
packages/airnode-protocol/scripts/verify-local.ts

verify deterministic deployment

---

.changeset/fifty-otters-heal.md
.changeset/happy-cycles-press.md
packages/airnode-deployer/terraform/aws/main.tf
packages/airnode-deployer/terraform/aws/modules/function/main.tf
packages/airnode-deployer/terraform/aws/modules/function/variables.tf
packages/airnode-deployer/terraform/aws/outputs.tf
packages/airnode-deployer/terraform/aws/variables.tf
packages/airnode-deployer/terraform/gcp/main.tf
packages/airnode-deployer/terraform/gcp/modules/function/main.tf
packages/airnode-deployer/terraform/gcp/modules/function/variables.tf
packages/airnode-deployer/terraform/gcp/outputs.tf
packages/airnode-deployer/terraform/gcp/variables.tf

Backport of https://github.com/api3dao/airnode/pull/1702

v0.10 - Fix Terraform secrets parsing & URLs propagations

---

packages/airnode-protocol/package.json
packages/airnode-protocol/scripts/write-example-env-file.ts
yarn.lock

I worked on this on a separate branch but it ended up being quite simple

Bump @api3/chains version to 2.0.0

---

.changeset/tiny-years-move.md
packages/airnode-node/package.json
packages/airnode-validator/package.json
packages/airnode-validator/src/api/api.ts
yarn.lock

Closes #1960.
Edit: WIP as something appears to have broken in the [E2E test](https://github.com/api3dao/airnode/actions/runs/8107515233/job/22159357673#step:5:177).

Use secret interpolation from api3/commons

---

.changeset/blue-starfishes-help.md
packages/airnode-node/src/evm/fulfillments/api-calls.test.ts
packages/airnode-node/src/evm/fulfillments/api-calls.ts

Backport of #2001 to the v0.14 branch, part of #2002

[v0.14] Add extra gas to account for EIP-150 reserved gas
