api3dao/airnode

packages/node/README.md
packages/node/src/core/evm/authorization/authorization-application.test.ts
packages/node/src/core/evm/authorization/authorization-application.ts
packages/node/src/core/evm/gas-prices.test.ts
packages/node/src/core/evm/gas-prices.ts
packages/node/src/core/evm/providers/index.ts
packages/node/src/core/evm/providers/initialize.ts
packages/node/src/core/evm/providers/process-transactions.ts
packages/node/src/core/providers/index.ts

Hopefully the last part of my decoupling work. There are probably more things that could be done but I think I want to stop here for now
Highlights:
1. Extract EVM specific provider functions (initialize and submit-transactions) to the `evm/` directory.
2. Remove useless `null` elements from the tuples that get returned from transaction-related functions
3. The `getGasPrice` function now only needs the contract address for the gas price feed and the ethers `provider` instead of the entire state.

Extract EVM specific provider code and decouple gas price fetching

---

packages/node/src/core/adapters/http/worker.test.ts
packages/node/src/core/evm/retry-provider.ts
packages/node/src/core/evm/workers.test.ts
packages/node/src/core/workers/cloud-platforms/aws.test.ts
packages/node/src/core/workers/cloud-platforms/aws.ts

Fixes Lambda function name build order as `airnode-${providerIdShort}-${stage}-${functionName}`

Fix lambda function names

---

packages/node/src/core/evm/handlers/initialize-provider.ts
packages/node/src/core/evm/providers.test.ts
packages/node/src/core/evm/providers.ts
packages/node/src/core/providers/initialize.test.ts
packages/node/src/core/providers/state.test.ts
packages/node/src/core/providers/state.ts
packages/node/src/types.ts
packages/node/test/fixtures/config/node-settings.ts
packages/node/test/fixtures/provider-states/evm.ts

- Renames `adminAddressForCreatingProviderRecord` as `providerAdminForRecordCreation` to conform to the [`config.json` docs](https://github.com/api3dao/api3-docs/blob/master/airnode/2-7-config-json.md)
- Sets a `gasLimit` of `300,000` while estimating gas for provider record creation. `estimateGas` fails if `gasLimit * getGasPrice()` is larger than the master wallet balance. Sometimes `ethers` (or whatever is doing this in the background) picks absurdly large `gasLimit`s, which may result in the gas estimation failing even if the master wallet balance is decent like 0.1 ETH. I didn't encounter this here specifically, but still, setting a large `gasLimit` as such doesn't really have any downsides in this context.

Fix provider admin config name

---

packages/node/src/core/coordinator/calls/aggregation.test.ts
packages/node/src/core/coordinator/calls/aggregation.ts
packages/node/src/core/evm/handlers/initialize-provider.ts
packages/node/src/core/handlers/start-coordinator.ts
packages/node/src/core/requests/request.test.ts
packages/node/src/core/requests/request.ts

1. API calls that are not pending will no longer be considered when aggregating before HTTP calls are made
2. Fix some incorrect logging messages when API calls or withdrawals are not actionable.
a. API calls must be either "pending" or "errored" to be considered actionable.
b. Withdrawals must be "pending" to be considered actionable.

Ignore requests that are not actionable

---

Docker.md
packages/deployer/src/evm/evm.ts
packages/node/src/evm/contracts/airnode.ts
packages/node/src/evm/contracts/convenience.ts
packages/protocol/index.js

- Unrolled protocol contract artifact dependencies and hardcoded them so that they are added to the package by `serverless-plugin-optimize`
- I copied the additions from https://github.com/api3dao/airnode/blob/operation-package/packages/protocol/index.js in advance. However I exported the artifacts more explicitly as `AirnodeArtifact` instead of `Airnode` instead of importing them with aliases later because the names `Airnode`/`Convenience` are already used (as in https://github.com/api3dao/airnode/blob/operation-package/packages/node/src/evm/contracts/airnode.ts#L2).

Hardcode artifact dependencies

---

packages/node/src/evm/transaction-counts.test.ts
packages/node/src/evm/verification/request-verification.test.ts
packages/node/src/evm/wallet.test.ts
packages/node/src/evm/wallet.ts

I think we miscommunicated about this. It's better to use `m/0/#` as the path because it cuts down on running time, we definitely won't need more than 2^31 requesters and we can still extend this by using `m/0/*/...`.
The designated wallet addresses updated in the tests are calculated with a separate script.

Fix designated wallet derivation convention

---

packages/deployer/src/config-data/config.json.example
packages/deployer/src/handlers/aws/index.ts
packages/node/__dev__/config.json.example
packages/node/src/adapters/http/worker.test.ts
packages/node/src/coordinator/calls/aggregation.ts
packages/node/src/evm/workers.test.ts
packages/node/src/types.ts
packages/node/src/workers/cloud-platforms/aws.test.ts
packages/node/src/workers/cloud-platforms/aws.ts
packages/node/test/fixtures/config/config.ts

- Changed the `triggers` field from `requests` to [`request`](https://github.com/api3dao/api3-docs/blob/master/airnode/config-json.md#triggers)
- AWS Lambda InvocationResponse is
```ts
export interface InvocationResponse {
StatusCode?: Integer;
FunctionError?: String;
LogResult?: String;
Payload?: _Blob;
ExecutedVersion?: Version;
}
```
where `data` is in `Payload` under `body` in stringified form. So updated the worker to return the parsed `data` and updated the related tests.
- `ApiCall` was stringifying the response unlike the provider functions causing inconsistency, so removed that.

Lambda fixes

---

packages/node/src/evm/authorization/authorization-fetching.test.ts
packages/node/src/evm/authorization/authorization-fetching.ts
packages/node/src/evm/templates/template-fetching.test.ts

I'm targeting the template-fallback branch for now. There are still a few outstanding comments so I haven't merged it yet
1. Falls back to individual authorization calls when the authorization batch call fails twice.
https://github.com/api3dao/airnode/issues/64

Authorization fetching fallback

---

packages/node/__dev__/config.json.example

Discussed with @bbenligiray that info field is not valid in apiSpecifications

info field is not valid in apiSpecifications

---

Dockerfile
Dockerfile-client
package.json

Closes #222
Using 14.16.0-alpine3.13 rather than 14.16.0-alpine3.12 because 14.16.0-alpine3.12 was giving errors and was not able to run the docker.
No breaking changes in the codebase.
Tested:
- Building and running all the repo tests.
- Running dev:invoke locally
- Running dockerfile-client (pushed a branch with node14 so the git clone of the docker was getting the new version)
After: 
https://github.com/api3dao/airnode/pull/243 is merged
We should merge pre-alpha into master for having #222 #228 and #224 into master (will create an issue for tracking)

Update to Node 14

---

package.json

Can't install without a valid "version" in `package.json`
```cli
❯ yarn add https://github.com/api3dao/airnode                                           ─╯
yarn add v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
error Can't add "airnode": invalid package version undefined.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Add initial `version` 0.1.0 to `package.json`

---

Docker-client.md
Dockerfile-client

Tested it using a config.json and .env in the root directly and it was successfully fulfilling requests.
Closes #228 
and 
Closes #224

Standardize the .env file used by airnode-client and implements healthcheck

---

packages/ois/src/types.ts

Const assertions will automatically resolve string literals without the need to explicitly and manually typecast
For instance:
```ts
import { OIS } from "./types";
import json from "./ois.json";
const example: OIS = json;
```
Will raise a type error as a string is not automatically assignable to either a product union or an enum.

Prefer `const assertions` over `type unions`

---

.github/workflows/build-test.yml

I had a look why https://github.com/api3dao/airnode/pull/271 has passed the CI checks and was able to be merged.
The reason is that @sitch is using forked repo and.
1) He `pushed` the commit in his repo - not triggering any CI, because it is a fork.
2) He opened a PR, but against airnode repo - but CI `build-test` workflow runs only on push.
This will make the workflow execute on PR against master as well.

Fix CI build-test script to make it run on PR against master

---

packages/node/src/evm/authorization/authorization-fetching.test.ts
packages/node/src/evm/handlers/initialize-provider.test.ts
packages/node/src/evm/initialization.test.ts
packages/node/src/evm/workers.test.ts

Took a look at the tests and:
- Corrected test name to `fetches group authorization status if it can be fetched`
- Remove duplicated `does nothing if unable to verify or set Airnode parameters` test
- Tests which are copy pasted can be written in a for each pattern.

Simplify tests

---

packages/deployer/webpack.config.js

After we started bundling the node with our own webpack configuration, ethers started throwing `SERVER_ERROR: missing response`. See https://github.com/ethers-io/ethers.js/issues/1108 for details.
This PR applies this workaround https://github.com/ethers-io/ethers.js/issues/1108#issuecomment-731039919
As https://github.com/ethers-io/ethers.js/issues/1108#issuecomment-731041031 predicts, this increases the bundled file size from 7.7MB to 8.3MB. Not a huge deal.

Fix ethers bundling

---

packages/node/__dev__/invoke.ts
packages/node/package.json
packages/node/src/utils/promise-utils.test.ts
packages/node/src/utils/promise-utils.ts

We only use Bluebird for promise timeouts. After some investigation and comments by @Siegrift it seemed like it could be replaced with native JS promises (using `Promise.race`). The initial comments are no longer applicable

Replace Bluebird with native promise implementation

---

docker/Dockerfile
docker/entrypoint.sh
packages/deployer/src/handlers/aws/index.ts
packages/deployer/src/infrastructure/index.ts
packages/deployer/terraform/airnode/main.tf
packages/deployer/terraform/airnode/modules/function/main.tf
packages/deployer/terraform/airnode/variables.tf

At first, I wanted to install the deployer from registry but decided against it. I think it would complicate the development and container testing process. So, I decided to build the deployer during the container build. But just the deployer, its dependencies are pulled from the registry. It felt like a nice compromise but I'm open to suggestions.
The resulting Docker image is around 500MB big and that's as low I was able to get due to all the dependencies.
I'm using [`su-exec`](https://github.com/ncopa/su-exec) to run deployer as user/group specified via `USER_ID`/`GROUP_ID` environment variables in order to set the correct access rights for the `receipt.json` output.
I'm providing a build argumment `yarnRegistry` that can be set to a custom Yarn respository URL for testing purposes.
As …

 Update deployer Dockerization process

---

.prettierignore
packages/protocol/contracts/authorizers/Api3Authorizer.sol
packages/protocol/contracts/authorizers/SelfAuthorizer.sol
packages/protocol/contracts/authorizers/interfaces/IApi3Authorizer.sol
packages/protocol/contracts/authorizers/interfaces/ISelfAuthorizer.sol
packages/protocol/test/authorizers/Api3Authorizer.sol.js
packages/protocol/test/authorizers/SelfAuthorizer.sol.js

This new Authorizer has a bool `airnodeIdToClientAddressToWhitelist`  that can be set along with the expiration. The client is only authorized if both the bool and the expiration satisfy. The `setWhitelistExpiration` can both set and unset `airnodeIdToClientAddressToWhitelist` thereby granting/revoking the whitelisting.  
The  old isAuthorized tests seem to be worded wrong, I've updated them but they should be changed

update authorizer contract and tests according to new specs

---

packages/protocol/test/AirnodeParameterStore.js
packages/protocol/test/AirnodeRrp.sol.js
packages/protocol/test/AirnodeRrpClient.sol.js
packages/protocol/test/Convenience.sol.js
packages/protocol/test/RequesterStore.sol.js
packages/protocol/test/authorizers/Api3Authorizer.sol.js
packages/protocol/test/authorizers/SelfAuthorizer.sol.js

In a recent PR, I removed some `context()` functions as I mistakenly thought the `protocol` package was using Jest. The `protocol` package uses `hardhat` which in turn uses Mocha. This PR reverts this change.

Use context instead of describe

---

packages/operation/src/evm/deploy/account-assignment.ts
packages/operation/src/evm/deploy/airnodes.ts
packages/operation/src/evm/deploy/requesters.ts
packages/operation/src/evm/deploy/state.ts
packages/operation/src/evm/requests/make-requests.ts
packages/operation/src/evm/utils.ts
packages/operation/src/types.ts

Had to disable `functional/no-let` es-lint rule because I wanted to use a for loop. Only disabled the rule in that particular line and not in the local es-lint file because I get the feeling that this function might be moved to a shared package since it's being used in multiple places.
Tests:
ran successfully:
1. `dev:background`
2. `dev:eth-deploy`
3. `dev:eth-requests`
`dev:invoke` failed because node package needs to be fixed first.

Fixes operation package after removing airnodeAdmin and requesterAdmin from the protocol contracts

---

packages/protocol/contracts/rrp/ConvenienceUtils.sol
packages/protocol/contracts/rrp/interfaces/IConvenienceUtils.sol
packages/protocol/test/ConvenienceUtils.sol.js

I wanted to make both mappings `public` in order to get automagic getters for them but I ended up creating `getAirnodePublicKey` and `getAirnodeAuthorizers` functions because the automatic getter for `airnodeToAuthorizers` was expecting 2 arguments (airnode address and index for authorizer array).
I expect `setAirnodePublicKey` to be called maybe only once while `setAirnodeAuthorizers` multiple times.

Splits airnodeToAnnouncement mapping into airnodeToPublicKey and airnodeToAuthorizers mappings

---

packages/protocol/contracts/admin/interfaces/IWhitelister.sol
packages/protocol/contracts/rrp/ConvenienceUtils.sol
packages/protocol/contracts/rrp/authorizers/interfaces/IApi3RequesterRrpAuthorizer.sol
packages/protocol/contracts/rrp/interfaces/IConvenienceUtils.sol
packages/protocol/test/ConvenienceUtils.sol.js

Public key and extended public key are different things, so renamed references to the public key as xpub.
We only need a getter for the authorizers, so made the xpub mapping public and removed the respective getter.
Please review and merge yourselves.

Xpub fixes

---

packages/deployer/README.md

Part of #462
I know this isn't much of a change but I looked through the Airnode starter docs and it feels like pretty much the same thing to me.
Also, I don't think it's our place to suggest some IAM setup for the users. Even the example from the video is just one way to do it. I mean, yes, we're basically providing a service they can run on AWS but it's still their infrastructure. I'd say that if you want to run something on AWS you should know how users and permissions work anyway.
But I'm open to suggestions.

Update deployer README - add AWS IAM setup video link

---

packages/deployer/src/cli/commands.ts
packages/deployer/src/infrastructure/index.ts
packages/deployer/terraform/airnode/main.tf
packages/deployer/terraform/airnode/modules/apigateway/outputs.tf
packages/deployer/terraform/airnode/modules/function/main.tf
packages/deployer/terraform/airnode/modules/function/variables.tf
packages/deployer/terraform/airnode/outputs.tf
packages/node/src/reporting/heartbeat.ts

Not entirely sure that writing the URL to `receipt.json` is ok but we don't really have any other choice how to let user know what the testing URL is.

Return testing gateway URL

---

packages/protocol/README.md
packages/protocol/contracts/rrp/WithdrawalUtils.sol
packages/protocol/contracts/rrp/interfaces/IWithdrawalUtils.sol
packages/protocol/test/WithdrawalUtils.sol.js

AirnodeRrp caller will no longer be able to set a destination and funds from sponsored wallet will be sent to the sponsor (account that created the withdrawal request prior to airnode fulfilling it with sponsored wallet)

Remove withdrawal destination

---

packages/node/src/evm/contracts/airnodeRrp.test.ts
packages/node/src/evm/contracts/airnodeRrp.ts
packages/node/src/evm/handlers/fetch-pending-requests.test.ts
packages/node/src/evm/handlers/initialize-provider.test.ts
packages/node/src/evm/requests/api-calls.test.ts
packages/node/src/evm/requests/api-calls.ts
packages/node/src/evm/requests/event-logs.ts
packages/node/src/evm/requests/events.ts
packages/node/src/evm/requests/withdrawals.test.ts
packages/node/src/evm/requests/withdrawals.ts
packages/node/src/handlers/start-coordinator.test.ts
packages/node/src/types.ts
packages/node/test/e2e/client-fulfill.feature.ts
packages/node/test/e2e/no-duplication.feature.ts
packages/node/test/e2e/request-status.feature.ts
packages/node/test/e2e/withdrawals.feature.ts
packages/node/test/fixtures/evm/event-logs.ts

These changes will not guarantee that all tests and code related to protocol events will pass/work but they will get us one step closer to getting the node package to compile again and be able to run tests as well as start the app.
Changes in protocol event names:
- ClientFullRequestCreated -> MadeFullRequest
- ClientRequestCreated -> MadeTemplateRequest
- ClientRequestFailed -> FailedRequest
- ClientRequestFulfilled -> FulfilledRequest
- WithdrawalFulfilled -> FulfilledWithdrawal
- WithdrawalRequested -> RequestedWithdrawal

Fixes protocol event names

---

packages/node/src/evm/authorization/authorization-fetching.test.ts
packages/node/src/evm/authorization/authorization-fetching.ts
packages/node/src/evm/handlers/initialize-provider.ts

AirnodeRrp.checkAuthorizationStatus() no longer needs designatedWallet being passed but it does need the authorizers address array to be passed as argument. I'm using the authorizers list defined in config.json under chain config.

AN-90: Fixes call to AirnodeRrp.checkAuthorizationStatus()

---

packages/admin/README.md
packages/node/src/providers/actions.test.ts

Related to #424.
Pocket doesn't support Ropsten, I see there are a few tests using Ropsten (I guess because there are contracts deployed on it already).
Do you guys have also the same contracts deployed to Rinkeby so we can update those Infura Ropsten references with Pocket Ethereum Rinkeby?
As discussed in the issue, I'll also submit PRs to [admin package](https://github.com/api3dao/airnode/tree/master/packages/admin) and [api3-docs](https://github.com/api3dao/api3-docs).

docs: update provider urls with Pocket

---

packages/node/test/setup/e2e/deployment.ts
packages/operation/README.md

Everything has been taken care in regards to endorser->sponsor renaming. Documentation update is the only thing left here.
All I was able to find was a comment and a link to https://github.com/api3dao/api3-docs/blob/master/request-response-protocol/endorsement.md. I remember that something like "READMEs should not have a dependency to docs" therefore I removed all the links in the operation package README.

AN-98: Replace endorsing with sponsoring

---

packages/node/__dev__/config.json.example
packages/node/src/evm/authorization/authorization-fetching.test.ts
packages/node/src/evm/authorization/authorization-fetching.ts
packages/node/src/evm/fulfillments/api-calls.ts
packages/node/test/fixtures/config/config.ts
packages/node/test/fixtures/operation/deploy-config.ts
packages/node/test/fixtures/provider-states/evm.ts
packages/node/test/setup/e2e/utils.ts
packages/operation/README.md
packages/operation/src/config/evm-dev-config.json
packages/operation/src/evm/deploy/deployment.ts
yarn.lock

Fix: 
Skips calling AirnodeRrp.checkAuthorizationStatuses when authorizers array is empty and returns true for all pending requests.
Operation package commands should be back to working condition.
@Siegrift Please checkout the branch and run the e2e locally. For some weird reason requester-fulfill.feature tests started to pass automagically. 
We can also work on a separate branch for fixing e2e since this is actually for fixing public authorizers.

AN-130: Skip authorization checks if authorizers is empty array

---

packages/adapter/src/request-building/build-request.test.ts
packages/adapter/src/request-building/parameters.test.ts
packages/adapter/src/request-building/parameters.ts
packages/adapter/src/types.ts
packages/adapter/test/fixtures/options.ts
packages/node/src/handlers/call-api.test.ts
packages/node/src/handlers/call-api.ts

Relay metadata parameters are not included in http requests even after properly configuring the airnode
When implementing this feature I made the wrong assumption that adding the parameters to the reservedParameters list in [call-api.ts](https://github.com/api3dao/airnode/blob/1c94313f636da4c7f4e08baf6327fc24cb46c8df/packages/node/src/handlers/call-api.ts#L83) was enough and that they were going to be sent on http requests. This was not properly tested and the metadata parameters where ignored and never included.
So I've created a new method on the adapters package to include them and tested both GET and POST requests using the operation package tools. Confirmed that the values reached the api by console logging the querystring when request was a GET and body when request was a POST.
Also …

Fixes relay metadata parameters

---

packages/protocol/contracts/rrp/AirnodeRrp.sol
packages/protocol/test/AirnodeRrp.sol.js
packages/protocol/test/requesters/RrpBeaconServer.sol.js

Fixes ARO-02 by adding airnode to the requestId hash calculation.
I'll cherry pick this merge commit and apply it to beta-protocol-revision branch too.

A3P-22: Certik ARO-02 | requestId should include airnode

---

packages/node/src/evm/handlers/initialize-provider.ts
packages/node/src/evm/verification/request-verification.test.ts

It was really easy to apply this verification because [verifySponsorWallets](https://github.com/api3dao/airnode/blob/b7debcfcdad90e0d1c15fcd5becf7ec5f18f36ed/packages/node/src/evm/verification/request-verification.ts#L8) function was written in a way that supported any type of requests. Simply amazing!

AN-69: Verify sponsor wallets for withdrawal requests

---

packages/protocol/contracts/rrp/AirnodeRrp.sol
packages/protocol/test/AirnodeRrp.sol.js
packages/protocol/test/requesters/RrpBeaconServer.sol.js

A [decision](https://api3workspace.slack.com/archives/C027Y2FAV0S/p1631374192018100) was made to ignore ARO-02 (add `airnodeAddress` to `requestId` hash) in order to be consistent with upcoming pub-sub protocol when generating a new hash for `requestId` but we will be adding the `sponsorAddress` to this hash.

A3P-23: Replace airnode with sponsor when generating requestId hash

---

packages/deployer/terraform/airnode/main.tf

As I was testing Airnode starter I realized that when I deploy Airnode without the HTTP gateway, the lambda that is called by the gateway is deployed anyway, even though nothing will ever call it. This fixes that.

Fix testing lambda deployment

---

package.json

Links for binaries were not created due to the fact that before the TS build there is nothing to be linked. This will force the creation. Needed mainly for the new Airnode starter.

Force linking of unbuild binaries

---

package.json
scripts/make-cli-executable.ts

https://api3dao.atlassian.net/browse/AN-230
Cause of the issue: https://github.com/microsoft/TypeScript/issues/37583
I think we have only 4 CLI tools as of now - unfortunately we will have to think about this issue when adding new CLI tools.

Add executable flag to CLIs

---

packages/protocol/README.md
packages/protocol/contracts/rrp/AirnodeRrp.sol
packages/protocol/contracts/rrp/interfaces/IAirnodeRrp.sol
packages/protocol/test/rrp/AirnodeRrp.sol.js
packages/protocol/test/rrp/requesters/RrpBeaconServer.sol.js
packages/protocol/test/rrp/requesters/RrpRequester.sol.js

- Require the Airnode wallet to sign the hash of `requestId` and `data`
- Reordered the `fulfill()` arguments
- Remove `xpub` announcement functionality (I was meaning to do this but this makes even more sense now, because in theory, multiple HD wallets with different seeds/xpubs can serve requests made to a single Airnode address as long as they have the Airnode sign the payload)
- Moved where the nonce is incremented in `makeTemplateRequest()`, not really important
I'm okay with waiting for https://github.com/api3dao/airnode/pull/577 to be merged before opening this PR, let me know if you think we should be doing something else

Require Airnode signatures for fulfillments

---

packages/examples/integrations/coingecko-testable/config.json
packages/examples/integrations/coingecko/config.json

Field `ois.[0].apiSpecifications.security` should no longer be present in the `config.json`.

Remove `ois.[0].apiSpecifications.security` field from example configs

---

.github/workflows/build-test.yml

The CI `yarn run bootstrap` step is taking ~60-90s each CI run. When the `yarn.lock` files aren’t modified in a PR, we can restore cached dependencies to avoid the install portion of this step and save the vast majority of that time. [Source](https://github.com/actions/cache/blob/main/examples.md#node---lerna).  
The restore key is based on key: `${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}` where `**` indicates any `yarn.lock` file in the repository. Consequently if any `yarn.lock` file changes there will be a cache miss and the install will run anew. 
Tested on my fork to restore the cache when there aren't `yarn.lock` changes, which speeds up this step quite a bit (10s restore + 4s `yarn run bootstrap`). Also tested to confirm a fresh install after a `yarn.lock` change.

Add lerna caching to CI

---

.github/workflows/build-test.yml
.github/workflows/mlc_config.json

The Continuous Build workflow fails somewhat frequently because of 429 "Too Many Requests" errors returned when checking many github.com links. This PR adds a retry with delay.

Add retryOn429 for CI doc link checking

---

packages/airnode-deployer/config/config.json.example
packages/airnode-examples/README.md
packages/airnode-examples/integrations/coingecko-testable/README.md
packages/airnode-examples/integrations/coingecko-testable/config.json
packages/airnode-examples/integrations/coingecko/config.json
packages/airnode-validator/test/validatorTests/endpoints.json
packages/airnode-validator/test/validatorTests/multipleOIS.json

Updates `endpointId` in airnode examples and other places where it was hardcoded with an invalid hash value

AN-333: Fix endpoint ID derivation implementation

---

docker/Dockerfile

Moving the `wget` commands further down in the `Dockerfile` inserts the files in the appropriate layer for HardHat.
HardHat also requires the appropriate `list.json` file for checksum verification.
Surprisingly opaque problem, easy solution.

AN-364: Fix docker build command - solidity compiler download.

---

packages/airnode-deployer/src/handlers/aws/index.ts
packages/airnode-node/src/adapters/http/index.ts
packages/airnode-node/src/adapters/index.ts
packages/airnode-node/src/evm/handlers/index.ts
packages/airnode-node/src/evm/index.ts
packages/airnode-node/src/evm/requests/index.ts
packages/airnode-node/src/index.ts
packages/airnode-node/src/requests/index.ts
packages/airnode-operation/src/config/evm-dev-config.json
packages/airnode-protocol/contracts/rrp/requesters/RrpBeaconServer.sol
packages/airnode-protocol/src/index.ts
packages/airnode-protocol/test/rrp/requesters/RrpBeaconServerWithManager.sol.js

@andreogle Airkeeper requires a few functions and types from airnode that are not currently being exported. I've exported only what's needed but we were wondering with Burak if we should be exporting everything by default.
@bbenligiray maybe I should have done this in a separate PR but I've also updated the RrpBeaconServer contract to support reading the beacon value with address(0) using the VoidSigner discussed [here](https://api3workspace.slack.com/archives/C027Y2FAV0S/p1637666522074300).

Exports things needed by Airkeeper and updates beacon reader condition

---

.changeset/moody-tools-thank.md
packages/airnode-deployer/README.md
packages/airnode-deployer/docker/Dockerfile
packages/airnode-deployer/package.json
packages/airnode-deployer/src/entrypoint.ts
packages/airnode-deployer/src/handlers/gcp/index.ts
packages/airnode-deployer/src/infrastructure/index.ts
packages/airnode-deployer/terraform/airnode/aws/main.tf
packages/airnode-deployer/terraform/airnode/aws/modules/function/main.tf
packages/airnode-deployer/terraform/airnode/gcp/main.tf
packages/airnode-deployer/terraform/airnode/gcp/modules/function/data.tf
packages/airnode-deployer/terraform/airnode/gcp/modules/function/main.tf
packages/airnode-deployer/terraform/airnode/gcp/modules/function/outputs.tf
packages/airnode-deployer/terraform/airnode/gcp/modules/function/variables.tf
packages/airnode-deployer/webpack.config.js
packages/airnode-node/package.json
packages/airnode-node/src/workers/cloud-platforms/aws.test.ts
packages/airnode-node/src/workers/cloud-platforms/gcp.test.ts
packages/airnode-node/src/workers/cloud-platforms/gcp.ts
packages/airnode-node/src/workers/index.ts
yarn.lock

Issues [AN-307](https://api3dao.atlassian.net/browse/AN-307), [AN-309](https://api3dao.atlassian.net/browse/AN-309)
I was able to include AN-309 as it wasn't that hard to do and testing was much easier that way.
Main changes:
* Added full support for GCP cloud (except HTTP gateway) - you can now deploy Airnode to GCP via deployer (just CLI, there may be some changes needed to support credential passing for containers)
* Extracted common handler to be available in the root of cloud function (needed by GCP)
* Added possible `import` step to the Terraform flow (needed because of the GCP's AppEngine)
* Increase AWS lambdas memory size - both AWS and GCP functions were failing for me on 128 MB memory limit so I set both to 256 MB. This will probably change soon anyway based on the stress test …

Add support for GCP cloud provider

---

packages/airnode-examples/test/e2e/coingecko-local.feature.ts
packages/airnode-examples/tsconfig.json

I realized that the examples were using Mocha typings instead of Jest typings.
This PRs fixes that (by not including hardhat.config.json in the TS sources - this is preferable since there are no mocha tests).
Also moves the test file in the e2e folder for conistency with other modules.

Fix jest typings in test, use consistent e2e folder structure

---

packages/airnode-deployer/src/infrastructure/index.ts

Issue [AN-413](https://api3dao.atlassian.net/browse/AN-413)
I made it so the warning is displayed only in the debug mode and with the correct wording (saying `Warning` not an `Error`). When not in debug mode, there is no indication of failure. I think this is fine since we expect to possibly fail only the Terraform `import` command and nothing else. All the other commands will fail with an exception.
The screenshot is made with mock commands just to showcase the fix.

Fix deployer warning message for unsuccessful Terraform import

---

.prettierignore

CHANGELOG files are auto-generated and don't need to be maintained by users, so there is no need to include them when Prettier is run. This is interfering with the release process: https://github.com/api3dao/airnode/runs/4444927728?check_suite_focus=true

Ignore CHANGELOG.md files with Prettier

---

packages/airnode-examples/integrations/coingecko/config.example.json
packages/airnode-validator/templates/0.4/config.json

- Corrected validator specification for v0.4 to make gas price fields optional
- Removed optional fields from one example to create a negative test case for the future

Minor correction to validator specification for v0.4

---

packages/airnode-validator/README.md

As per the discussion in AN-407 the monorepo package should now retain any manual build instructions. The docs will have the content regarding things such as npx and Docker image usage. The manual build instructions have already been removed (see AN-406) and the reference to a manual build now is linked back to the monorepo README.

Moving the manual build instructions back to the README.

---

.changeset/late-apples-decide.md
packages/airnode-deployer/src/infrastructure/index.ts
packages/airnode-deployer/terraform/state/aws/main.tf
packages/airnode-deployer/terraform/state/gcp/main.tf
packages/airnode-validator/exampleSpecs/secrets.config.json
packages/airnode-validator/templates/0.2/config.json
packages/airnode-validator/templates/0.3/config.json
packages/airnode-validator/templates/0.4/config.json

Close #757
There was a difference between how the bucket name is handled by the state recipes and airnode recipes (one was lowercasing the name and the second one wasn't), that's why it was possible to create a bucket but not find it afterward.
I united it so the bucket name is always lowercase but I would also like to force `stage` to contain only lower case characters (numbers and underscore `_` are ok) just to be on the safe side. I've already modified the validator templates.
@wkande Can you update the docs to reflect that?

Force stage deployment variable to be lowercase

---

packages/airnode-examples/README.md
packages/airnode-examples/test/utils.ts

I've tried running the examples on my new laptop (mac) and I came a cross issues:
a) the steps in examples do not fail early
b) I've forgot to change PROVIDER_URL (it's written in the docs, but could be more readable)
I've addressed both points.

Make airnode examples fail early, improve README

---

.changeset/pretty-files-notice.md
package.json
packages/airnode-deployer/jest.config.js
packages/airnode-deployer/src/cli/commands.ts
packages/airnode-deployer/src/handlers/aws/index.ts
packages/airnode-deployer/src/handlers/gcp/index.ts
packages/airnode-deployer/src/utils/files.ts
packages/airnode-deployer/src/utils/infrastructure.ts
packages/airnode-deployer/src/utils/validation.test.ts
packages/airnode-deployer/src/utils/validation.ts
packages/airnode-deployer/test/fixtures/config/config.ts
packages/airnode-deployer/test/fixtures/config/index.ts
packages/airnode-deployer/test/fixtures/config/node-settings.ts
packages/airnode-deployer/test/fixtures/config/ois.ts
packages/airnode-deployer/test/fixtures/index.ts
packages/airnode-deployer/test/setup/init/set-define-property.ts
packages/airnode-deployer/tsconfig.json
packages/airnode-node/src/config/index.ts
packages/airnode-node/src/workers/local-handlers.ts
packages/airnode-validator/src/validator.test.ts
packages/airnode-validator/src/validator.ts

Cam reported that`callApi` was timing out on AWS for the Amberdata deployment. I investigated and found that the size of the config file had surfaced severe inefficiencies in the `config.json` validator. This appears to only be an issue on cold-start of each handler (`parsedConfig` appears to effectively be memo’ised), but the inefficiency resulted in a start-up delay of 14-16 seconds, enough to prevent callApi from ever running.
After some investigation I found that the validator was largely responsible for this delay; disabling the validator in cloud environments reduces total execution time to the point that `callApi` no longer times out before the config has been parsed and memo'ised.
This PR implements disabling the validator in cloud environments.

Do not run the validator in cloud environments.

---

packages/airnode-examples/scripts/deploy-airnode.ts

I forgot to remove this one from examples when finishing https://github.com/api3dao/airnode/pull/749

Remove non existent flag from deployer in airnode examples

---

packages/airnode-deployer/terraform/airnode/aws/providers.tf
packages/airnode-deployer/terraform/state/aws/providers.tf

[Issue AN-481](https://api3dao.atlassian.net/browse/AN-481)
I bumped the version but this was actually not an issue. The `~>` in version description means that the provider should be of major version `3` and the highest available minor version. And in our setup, the providers are downloaded during the deployment, not during the Docker image build. So, even the older Docker images will use the newest provider.

Update AWS Terraform provider version

---

.changeset/violet-terms-unite.md
packages/airnode-deployer/docker/Dockerfile
packages/airnode-deployer/src/infrastructure/index.ts
packages/airnode-deployer/terraform/airnode/gcp/main.tf
packages/airnode-deployer/terraform/airnode/gcp/modules/function/main.tf
packages/airnode-examples/README.md
packages/airnode-examples/scripts/deploy-airnode.ts
packages/airnode-examples/scripts/remove-airnode.ts

[Issue AN-464](https://api3dao.atlassian.net/browse/AN-464)
Users will now need to enable just one API in GCP console and create a service account with the access key that can be downloaded as a JSON file to use for authentication. No need to install `gcloud` tools.
Docs update and further explanation of the new flow in [PR #532](https://github.com/api3dao/api3-docs/pull/532)

Update GCP authentication process & API management

---

.github/workflows/build-test.yml

The idea, which is to run skip the Action run for an internal PR since it's already covered by `push`  (hence why the tests currently run twice), originated from a comment [within this thread](https://github.community/t/duplicate-checks-on-push-and-pull-request-simultaneous-event/18012/5) and is currently being used [here](https://github.com/Dart-Code/Dart-Code/blob/master/.github/workflows/build-and-test.yml). 
Closes #295.
Update: you can see it worked in the "All checks have passed" section below where all of the `(pull_request)` steps are skipped, and all of the `push` steps were successful.

Avoid CI running 2X for push within an internal PR

---

packages/airnode-examples/README.md

While documenting https://github.com/api3dao/airnode/pull/764 I made a mistake and documented the withdrawal request after the Airnode is tear down. This of course will result in withdrawal request not processed. Kudos to Martin for testing and reporting this.
The order should be flipped.

Fix the order of commands in the examples package

---

packages/airnode-node/src/evm/gas-prices.ts

This adds a function wrapper around the gas pricing call, without this the underlying code references the wrong context.
Subject to testing by @jgcogsystematictrading
Fixes #798

Revert In-lined Gas Price Call

---

.changeset/famous-pigs-bathe.md
packages/airnode-examples/README.md
packages/airnode-examples/contracts/relay-security-schemes/Requester.sol
packages/airnode-examples/integrations/relay-security-schemes/README.md
packages/airnode-examples/integrations/relay-security-schemes/config.example.json
packages/airnode-examples/integrations/relay-security-schemes/create-config.ts
packages/airnode-examples/integrations/relay-security-schemes/create-secrets.ts
packages/airnode-examples/integrations/relay-security-schemes/request-utils.ts
packages/airnode-examples/integrations/relay-security-schemes/secrets.example.env
packages/airnode-validator/src/validators/validators.test.ts
packages/airnode-validator/templates/1.0/apiSpecifications.json

[AN-511](https://api3dao.atlassian.net/browse/AN-511)
Note the name `relay-security-schemes` was chosen as this is the nomenclature [used in the docs](https://docs.api3.org/airnode/v0.4/grp-providers/guides/build-an-airnode/api-security.html#supported-security-schemes).
Ignore the failing docs link check in CI- this will pass once merged.
Here is how the output looks:
```
> yarn make-request
yarn run v1.22.11
$ ts-node scripts/make-request.ts
Making request...
Waiting for fulfillment...
Request fulfilled
The following was successfully relayed:
requesterAddress: 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
sponsorAddress: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
sponsorWalletAddress: 0x68F7F1197a9FD5f2EC79B4eBff2879A1dc1fe78f
chainId: 31337
chainType: evm
Done in 20.31s.
```

Add relay security schemes example integration

---

packages/airnode-adapter/src/response-processing/extraction.test.ts

Adds a test for `_times` and adds another demonstrating empty string handling. Also fixes a few typos.
[AN-528](https://api3dao.atlassian.net/browse/AN-528)

Add tests for splitting multiple reserved parameters

---

.changeset/thin-parents-wash.md
.github/workflows/build-test.yml
packages/airnode-examples/README.md
packages/airnode-examples/package.json
packages/airnode-examples/scripts/create-airnode-secrets.ts
packages/airnode-examples/scripts/derive-and-fund-sponsor-wallet.ts
packages/airnode-examples/scripts/make-request.ts
packages/airnode-examples/scripts/make-withdrawal-request.ts
packages/airnode-examples/scripts/sponsor-requester.ts
packages/airnode-examples/test/e2e/coingecko-local.feature.ts
packages/airnode-examples/test/utils.ts

Closes https://github.com/api3dao/airnode/issues/812
Resolves these Jira issues:
* https://api3dao.atlassian.net/browse/AN-541
* https://api3dao.atlassian.net/browse/AN-542
I've also wanted to include a step of running airnode examples on CI, but this is unfortunately not possible, since you can't run linux containers on windows (see: https://github.community/t/github-actions-windows-runtime-linux-container-mode-docker/135874/4). This is compensated for windows and macOs users with the [Docker for desktop](https://www.docker.com/products/docker-desktop).

Fix airnode-examples for windows

---

.github/workflows/build-test.yml
.husky/pre-push
README.md
package.json

https://api3dao.atlassian.net/browse/AN-495
When this is merged, the changeset bot can be turned off (maybe @andreogle can do this).
You can see the code working on [my Airnode forked](https://github.com/Siegrift/airnode) with similar PR to this merged. You can see two PRs - one with empty changeset that is passing the CI and one that doesn't have any changeset and fails. (Check details, since both PRs actually fail on CI because of some static analyzer check)

Enforce changesets

---

.changeset/tame-oranges-clap.md
packages/airnode-deployer/docker/Dockerfile
packages/airnode-examples/scripts/create-airnode-secrets.ts
packages/airnode-examples/scripts/deploy-airnode.ts
packages/airnode-examples/scripts/remove-airnode.ts
packages/airnode-examples/src/utils.ts

This fixes the `airnode-deployer` build on Windows.
The problem was that Git on Windows, by default, swaps Unix end-of-line bytes with Windows _EOL_ bytes (LF vs CRLF), which makes `/entrypoint.sh` not executable (it breaks the shebang).
Ideally one would want to configure git to not do this, which is possible, but the process is inconsistent depending on which Git you're using (Git for Windows, Github Desktop, etc.) and seemingly has to be applied in the Dockerfile too. Using `sed`, a utility the Alpine image comes bundled with, to do the character removal, seems like an elegant one-line solution that doesn't noticeably increase the docker image size.
Git automatically converts files back to Unix when a Windows user does a commit and push.

Fix windows build by conforming line endings to Unix

---

.changeset/eight-roses-shave.md
packages/airnode-node/src/reporting/heartbeat.test.ts
packages/airnode-node/src/reporting/heartbeat.ts

Based on [slack discussion](https://api3workspace.slack.com/archives/C02AYRX8D89/p1635066629013200).
I tested it with the deployment created on staging and it became `Active` :slightly_smiling_face:

Fix heartbeat API key location & name

---

.changeset/fresh-teachers-compete.md
packages/airnode-utilities/package.json

`yarn pack` is an important command because it is used by the artifacts build process.
The lack of this command meant that `airnode-utilities` didn't make its way into the airnode-client image and hence e2e tests started failing.

Add back yarn pack to fix docker build process

---

.changeset/loud-clouds-lie.md
packages/airnode-examples/integrations/coingecko-signed-data/README.md

Removes the `\`, which was causing the curl command to return an internal server error.

Fix coingecko-signed-data integration command typo

---

packages/airnode-protocol-v1/contracts/dapis/DapiServer.sol
packages/airnode-protocol-v1/contracts/protocol/StorageUtils.sol
packages/airnode-protocol-v1/test/dapis/DapiServer.sol.js
packages/airnode-protocol-v1/test/protocol/StorageUtils.sol.js

The subscription struct has two dynamically sized fields, which makes the usage of `abi.encodePacked` inappropriate. It was replaced by `abi.encode` as a solution.
An alternative to this is to always use `abi.encode` as done in the pre-alpha contracts. Since we never store the encoded bytes, we don't need to care about its length.

Use standard packing for subscription ID derivation

---

packages/airnode-protocol-v1/contracts/monetization/RequesterAuthorizerWhitelisterWithToken.sol
packages/airnode-protocol-v1/test/monetization/RequesterAuthorizerWhitelisterWithTokenDeposit.sol.js
packages/airnode-protocol-v1/test/monetization/RequesterAuthorizerWhitelisterWithTokenPayment.sol.js

My initial plan for behavior was to only allow
```
(Any status) => OptedOut
```
or
```
OptedOut => Inactive
```
if the caller was `airnode` (but apparently I forgot to implement the second part). This felt a bit like unnecessarily complex, so I decided to allow the following instead
```
(Any status) => Inactive
```
or
```
(Any status) => OptedOut
```
This means that differently from the first version, `airnode` can set change its status as `Active => Inactive`, which is not really an issue (because `airnode` could already do that by opting out and opting back in). This made the implementation a lot simpler.

Allow Airnode to opt back in

---

packages/airnode-protocol-v1/contracts/monetization/RequesterAuthorizerWhitelisterWithTokenDeposit.sol
packages/airnode-protocol-v1/contracts/monetization/interfaces/IRequesterAuthorizerWhitelisterWithTokenDeposit.sol
packages/airnode-protocol-v1/test/monetization/RequesterAuthorizerWhitelisterWithTokenDeposit.sol.js

Implemented a lead time requirement to prevent front-running the block transaction, but kept it disabled by default assuming we will never need it. The lead time is capped at 30 days to prevent its abuse.

Implement optional lead time requirement for withdrawals

---

.changeset/fifty-bottles-suffer.md
packages/airnode-node/src/coordinator/calls/aggregation.test.ts
packages/airnode-node/src/coordinator/calls/disaggregation.test.ts
packages/airnode-node/src/coordinator/calls/disaggregation.ts
packages/airnode-node/src/evm/authorization/authorization-application.test.ts
packages/airnode-node/src/evm/authorization/authorization-application.ts
packages/airnode-node/src/evm/fulfillments/api-calls.test.ts
packages/airnode-node/src/evm/fulfillments/api-calls.ts
packages/airnode-node/src/evm/fulfillments/withdrawals.test.ts
packages/airnode-node/src/evm/requests/api-calls.test.ts
packages/airnode-node/src/evm/requests/api-calls.ts
packages/airnode-node/src/evm/templates/template-application.test.ts
packages/airnode-node/src/evm/templates/template-application.ts
packages/airnode-node/src/evm/verification/request-verification.test.ts
packages/airnode-node/src/evm/verification/request-verification.ts
packages/airnode-node/src/requests/request.test.ts
packages/airnode-node/src/requests/request.ts
packages/airnode-node/src/types.ts

[AN-482](https://api3dao.atlassian.net/browse/AN-482), part 4.
Potentially controversial changes include functions that previously accepted a single `Request<ApiCall>`, but now take `apiCalls: Request<ApiCall>[],` in order to use `reduce` to filter errored requests.

Remove Errored variant of RequestStatus enum

---

packages/airnode-protocol/src/index.ts

This line caused CI to fail for some reason (dunno why). This export is not used anywhere so we can remove it to unblock the CI (hopefully).

Remove unused export

---

.github/workflows/build-test.yml
.github/workflows/mlc_config.json
package.json
packages/airnode-protocol-v1/contracts/dapis/DapiServer.sol
packages/airnode-protocol-v1/hardhat.config.js
packages/airnode-protocol-v1/test/dapis/DapiServer.sol.js
packages/airnode-protocol/src/index.ts
yarn.lock

When we require `msg.sender==address(0)` this function can no longer change the state, which makes its name accurate

Require conditionPspDapiUpdate caller to be zero address

---

.changeset/shiny-moose-care.md
packages/airnode-node/src/evm/wallet.ts

This fixes `protocolId` in **deriveWalletPathFromSponsorAddress** to have a default value (from [here](https://github.com/api3dao/airnode/pull/944#discussion_r831052861))

Change protocolId to have default value

---

packages/airnode-protocol-v1/contracts/dapis/DapiServer.sol
packages/airnode-protocol-v1/contracts/dapis/interfaces/IDapiServer.sol
packages/airnode-protocol-v1/test/dapis/DapiServer.sol.js

Both for Beacons and dAPIs, the condition functions return `true` if the data point to be updated hasn't been initialized. This addresses the issue (even though it's not usable due to being front-runnable) where people can extract 1 bit from Beacon values by utilizing unintialized dAPIs. 
Also implemented a `updateDapiWithBeaconsAndReturnCondition()` with nicer interface. Note that it doesn't require `msg.sender==address(0)` because that`s not needed.

Update conditions always return true if the data point is not initialized

---

.changeset/three-schools-jam.md
packages/airnode-protocol/contracts/rrp/requesters/RrpRequester.sol
packages/airnode-protocol/contracts/rrp/requesters/interfaces/IAirnodeRrp.sol
packages/airnode-protocol/contracts/rrp/requesters/interfaces/IAuthorizationUtils.sol
packages/airnode-protocol/contracts/rrp/requesters/interfaces/ITemplateUtils.sol
packages/airnode-protocol/contracts/rrp/requesters/interfaces/IWithdrawalUtils.sol

I tried implementing a requester contract with Solidity 0.8.12 and realized that I can't because RrpRequester and the AirnodeRrp interfaces it depended on are fixed to 0.8.9. I updated the RrpRequester Solidity version to be ^0.8.0 but I couldn't do the same for AirnodeRrp interfaces because it changes the bytecode and breaks verifications. So I had to copy paste the AirnodeRrp interfaces to be used by RrpRequester. It's hacky but we can fix it in the v1 protocol.

Loosen Solidity version requirement for RrpRequester

---

.changeset/rude-clouds-draw.md
package.json
packages/airnode-deployer/terraform/airnode/gcp/main.tf

This bug explains why all of a sudden we needed to enable the API gateway service manually on GCP.
Related to [AN-698](https://api3dao.atlassian.net/browse/AN-698) and [AN-700](https://api3dao.atlassian.net/browse/AN-700). Not sure it's the only issue though.

Fix condition for enabling GCP API gateway service

---

.changeset/rude-clouds-draw.md
package.json
packages/airnode-deployer/terraform/airnode/gcp/main.tf

Applies https://github.com/api3dao/airnode/pull/1044 to the 0.6 release.

[v0.6]: Fix condition for enabling GCP API gateway service

---

.changeset/lucky-falcons-lay.md
packages/airnode-ois/src/index.ts
packages/airnode-validator/package.json
packages/airnode-validator/src/index.ts
packages/airnode-validator/test/cli.feature.ts
packages/airnode-validator/tsconfig.build-cjs.json
packages/airnode-validator/tsconfig.build-es6.json
packages/airnode-validator/tsconfig.build-esm.json
scripts/make-cli-executable.ts
yarn.lock

https://api3dao.atlassian.net/browse/AN-622
Added build targets for non cjs targets. This makes it more optimal to load the validator inside the browser environment (although modern bundles would probably handle cjs as well). 
I've tested this using a simple FE application and validator published locally (using verdaccio). I've also made sure the source maps works.

Improve validator bundling

---

.changeset/chilly-squids-jam.md
packages/airnode-validator/src/ois/ois.test.ts
packages/airnode-validator/src/ois/ois.ts

https://api3dao.atlassian.net/browse/AN-612
Ensures that interpolated path variables in config.json exist and also that every parameter is used (ensuring bijection).

Paths validation

---

.changeset/fifty-tools-attack.md
packages/airnode-adapter/src/request-building/authentication.test.ts
packages/airnode-adapter/src/request-building/authentication.ts
packages/airnode-node/src/api/index.test.ts
packages/airnode-node/test/fixtures/config/config.ts
packages/airnode-node/test/fixtures/config/ois.ts
packages/airnode-validator/src/api/api.ts
packages/airnode-validator/src/config/config.test.ts
packages/airnode-validator/src/config/config.ts
packages/airnode-validator/src/ois/ois.test.ts
packages/airnode-validator/src/ois/ois.ts
packages/airnode-validator/src/types.ts

[AN-614](https://api3dao.atlassian.net/browse/AN-614): used [zod.superRefine()](https://github.com/colinhacks/zod#superRefine) in order to validate that the security scheme enabled under `ois.apiSpecifications.security` is defined in `ois.apiSpecifications.components`.

AN-614: Allowed security scheme must exist in config.json

---

.changeset/warm-knives-visit.md
packages/airnode-examples/README.md
packages/airnode-examples/package.json
packages/airnode-examples/scripts/stop-local-airnode.ts
packages/airnode-node/docker/Dockerfile
packages/airnode-node/docker/entrypoint.sh
packages/airnode-node/package.json
packages/airnode-node/src/cli/validate-config.ts

[AN-595](https://api3dao.atlassian.net/browse/AN-595)
Doing the config file validation separately (instead of running it as a part of `invoke.ts`) so that if it fails, the container fails as well instead of running and throwing an error every minute.

Add config validation for local Airnode invocation including `airnode-client` container

---

package.json
tsconfig.json

https://api3dao.atlassian.net/browse/AN-743
- I've considered enabling the advanced checks similarly how I considered enabling them in Airseeker, but they are a bit restricting, so I've just explicitely disabled them.
- I haven't removed the `tsconfig.build.json` files simply because the current setup works and I do not see the refactor as worth it. 
- I've added a `compile` command which builds all of the projects - This runs TypreScript in all of the source files including tests. It's the most convenient way to check whether there are any TS errors in the project (because `build` only looks into source files without tests).

Update root tsconfig

---

.changeset/popular-kings-protect.md
packages/airnode-node/package.json

@Ashar2shahid found a bug in Airnode-node when using it within Airkeeper, relating to axios not being included as a dependency in package.json.

Add axios dependency in Airnode for Processing

---

.github/dependabot.yml

This PR adds @Siegrift and @aquarat as dependabot reviewers.

Add additional dependabot PR reviewers

---

.changeset/fast-kangaroos-bake.md
packages/airnode-validator/src/config/config.test.ts
packages/airnode-validator/src/config/config.ts

Rationale explained well by the ethers `BigNumber` [documentation](https://docs.ethers.io/v5/api/utils/bignumber/#BigNumber--notes-safenumbers).

Add upper bound to Amount numbers

---

.changeset/wise-pots-wait.md
packages/airnode-deployer/terraform/airnode/aws/main.tf
packages/airnode-deployer/terraform/airnode/gcp/main.tf

Backporting changes from https://github.com/api3dao/airnode/pull/1155 to v0.6

[v0.6] Adjust memory allocation for gateway serverless functions

---

.changeset/odd-poems-shout.md
packages/airnode-node/src/cli/validate-config.ts
packages/airnode-validator/src/api/api.test.ts
packages/airnode-validator/src/api/api.ts
packages/airnode-validator/src/cli/cli.test.ts
packages/airnode-validator/src/cli/cli.ts
packages/airnode-validator/test/cli.feature.ts
packages/airnode-validator/test/fixtures/invalid-secret-name/config.json
packages/airnode-validator/test/fixtures/invalid-secret-name/secrets.env

https://api3dao.atlassian.net/browse/AN-471
Turns out we already handle this. At first, I thought I will add a more descriptive error message (saying make sure the secret is a valid identifier), but this makes the error message inaccurate when there is a missing secret which will be the most common error. I've simplified the CLI error message a bit though.

Reject invalid secrets

---

.changeset/breezy-bees-tickle.md
packages/airnode-validator/src/api/api.test.ts
packages/airnode-validator/src/api/api.ts

[AN-776](https://api3dao.atlassian.net/browse/AN-776)
Note `emptySecret` has been removed from `interpolateSecrets` as the secrets are parsed first within `parseConfigWithSecrets` then interpolated so the `.min(1)` catches empty secrets.

Fail validation with empty secret value

---

tsconfig.json

See: https://api3workspace.slack.com/archives/C02AYRX8D89/p1656603015667139
The ES5 was not supported by IE which is dead now. The current problem
with es5 are custom exceptions which do not work properly when targeting
es5. THe best solution is to set the target to es6.
See details in:
https://www.dannyguo.com/blog/how-to-fix-instanceof-not-working-for-custom-errors-in-typescript/

Set TS config "target" to es6

---

renovate.json

The generated PR title of renovate PRs is pre-pends "Update ..." automatically so currently we have "Update Update ...". See https://github.com/api3dao/airnode/pull/1289
This fixes that.

Update renovate group names

---

.changeset/mean-taxis-sing.md
packages/airnode-adapter/src/types.ts
packages/airnode-adapter/test/fixtures/options.ts
packages/airnode-deployer/src/handlers/aws/index.ts
packages/airnode-deployer/src/handlers/gcp/index.ts
packages/airnode-node/src/adapters/http/worker.test.ts
packages/airnode-node/src/adapters/http/worker.ts
packages/airnode-node/src/api/index.test.ts
packages/airnode-node/src/api/index.ts
packages/airnode-node/src/api/processing.test.ts
packages/airnode-node/src/api/processing.ts
packages/airnode-node/src/coordinator/calls/aggregation.test.ts
packages/airnode-node/src/coordinator/calls/aggregation.ts
packages/airnode-node/src/evm/templates/template-verification.test.ts
packages/airnode-node/src/evm/verification/request-verification.ts
packages/airnode-node/src/evm/wallet.test.ts
packages/airnode-node/src/evm/wallet.ts
packages/airnode-node/src/handlers/call-api.test.ts
packages/airnode-node/src/handlers/call-api.ts
packages/airnode-node/src/handlers/process-http-request.test.ts
packages/airnode-node/src/handlers/process-http-request.ts
packages/airnode-node/src/handlers/process-http-signed-data-request.test.ts
packages/airnode-node/src/handlers/process-http-signed-data-request.ts
packages/airnode-node/src/types.ts
packages/airnode-node/src/workers/local-handlers.test.ts
packages/airnode-node/src/workers/local-handlers.ts
packages/airnode-node/test/fixtures/aggregated-api-call.ts

1. This is a draft PR because I've created a new branch out of `private-key-env` to be ahead of possible merge conflicts
2. Main change I did was limiting the required fields on the payload.config object by creating a [new type](https://github.com/api3dao/airnode/blob/f3c9957f8809629372009c97e758061c46ca41bb/packages/airnode-node/src/api/index.ts#L104-L108) using the typescript Pick utility type. I could have created a new type with only those required fields but I wanted to keep backwards compatibility with anyone calling this handler passing the whole config object.

AN-754: callApi handler argument refactor

---

renovate.json

See https://github.com/api3dao/airnode/issues/1259 which was automatically opened by renovate and is enabled by default, but we don't really need it. (I think once this is merged renovate will automatically close that issue. If not I'll close it manually).
I also noticed that the Airnode team assignment does not work as expected. There is a fix for that: https://github.com/renovatebot/renovate/discussions/11217

Disable renovate dependency dashboard, assign Airnode team as reviewer

---

.changeset/yellow-emus-remain.md
packages/airnode-deployer/terraform/airnode/gcp/main.tf

Turn off GCP service disabling when removing deployment to enable multiple deployments per project

---

.changeset/plenty-buttons-rhyme.md
packages/airnode-deployer/terraform/airnode/gcp/modules/function/main.tf
packages/airnode-deployer/terraform/airnode/gcp/modules/function/variables.tf
packages/airnode-examples/integrations/coingecko-testable/README.md

Close #1380
I tested both the regions and it works now. You provide the name from the documentation (with the `1` at the end) and we "translate" those two region names for the App Engine resource.

Fix naming for some of the GCP regions

---

.changeset/nice-shoes-happen.md
packages/airnode-node/src/workers/local-gateways/server.ts

Removes extra `/` that is present as shown below:
```sh
[2022-08-31 06:22:17.788] INFO HTTP signed data gateway listening for request on "http://localhost:3000/http-signed-data/:endpointId" 
[2022-08-31 06:22:17.793] INFO HTTP (testing) gateway listening for request on "http://localhost:3000//http-data/:endpointId"
```
Compare to: https://github.com/api3dao/airnode/blob/e592573a2434cc16e97812524955c50ae4ba0ead/packages/airnode-node/src/workers/local-gateways/server.ts#L54

Fix airnode-client httpGatewayPath

---

.changeset/cold-camels-clean.md
packages/airnode-examples/contracts/authenticated-coinmarketcap/Requester.sol
packages/airnode-examples/contracts/coingecko-post-processing/Requester.sol
packages/airnode-examples/contracts/coingecko-pre-processing/Requester.sol
packages/airnode-examples/contracts/coingecko-signed-data/Requester.sol
packages/airnode-examples/contracts/coingecko-template/Requester.sol
packages/airnode-examples/contracts/coingecko-testable/Requester.sol
packages/airnode-examples/contracts/coingecko/Requester.sol
packages/airnode-examples/contracts/failing-example/Requester.sol
packages/airnode-examples/contracts/relay-security-schemes/Requester.sol
packages/airnode-examples/contracts/weather-multi-value/Requester.sol

See the base RRP Requester constructor: https://github.com/api3dao/airnode/blob/master/packages/airnode-protocol/contracts/rrp/requesters/RrpRequesterV0.sol#L23

Fix wrong name in airnode-examples Requester contracts

---

.changeset/bright-ears-wonder.md
packages/airnode-protocol/test/rrp/AirnodeRrpV0.sol.js
packages/airnode-protocol/test/rrp/requesters/RrpRequesterV0.sol.js

I noticed that `fulfillData` is encoded wrong. This doesn't matter for the unit tests, but would matter if the data was to be decoded on chain. This might confuse users poking around the tests to learn how stuff works.

Correct test fixtures

---

.changeset/fifty-planes-sell.md
packages/airnode-deployer/terraform/aws/main.tf
packages/airnode-deployer/terraform/aws/modules/function/data.tf
packages/airnode-deployer/terraform/aws/modules/function/main.tf
packages/airnode-deployer/terraform/aws/modules/function/variables.tf
packages/airnode-deployer/terraform/gcp/modules/function/data.tf
packages/airnode-deployer/terraform/gcp/modules/function/main.tf
packages/airnode-deployer/terraform/gcp/modules/function/variables.tf

Close #1450
The first two commits are just some cleaning/minor refactor since I was going through the recipes anyway.
The last commit is the fix to #1450. The problem is in the [two lines](https://github.com/api3dao/airnode/blob/master/packages/airnode-deployer/terraform/aws/main.tf#L34-L35) that are passing the gateways' URLs to the coordinator's env variables. At this point, I'm almost certain that the dependency cycle error is a bug in Terraform and shouldn't happen. Even though the coordinator references the gateways (their output), the gateways don't reference the coordinator back, so there should not be any dependency cycle. I may create a minimal reproducible example and open it as an issue. The only solution that works is to condition the whole module instead of the individual …

Fix Terraform dependency cycle error when removing HTTP gateways

---

packages/airnode-protocol/package.json
packages/airnode-protocol/scripts/generate-references.ts
packages/airnode-protocol/scripts/tsconfig.json
packages/airnode-protocol/tsconfig.json
scripts/validate-ts-references.ts
yarn.lock

The protocol scripts were not TypeChecked by TS and the recent PR which removed all unnecessary async/await broke the script (you can't call `.then` on synchronous function).
This PR adds type checking to the protocol scripts and removes unnecessary wrapper for `generate-references` script.

Fix TS errors in generate-references script

---

.changeset/sharp-pianos-lie.md
packages/airnode-deployer/config/config.example.json
packages/airnode-deployer/test/fixtures/config.valid.json
packages/airnode-examples/src/scripts/choose-integration.ts
packages/airnode-examples/src/utils.test.ts
packages/airnode-examples/src/utils.ts
packages/airnode-node/src/providers/actions.test.ts

Closes https://github.com/api3dao/airnode/issues/1280

Remove ropsten/rinkeby references

---

.changeset/fresh-vans-relax.md
docker/entrypoint.sh
docker/scripts/utils.ts

Closes #1493.
Using `throw` within `NODE_OPTIONS='--unhandled-rejections=throw'` as [this is the default for node v15.0.0 and above](https://nodejs.org/api/cli.html#--unhandled-rejectionsmode).
I tested this by inserting `exit 1` before the airnode-admin `docker build` command. Without this PR's change, the build "succeeds" despite the error, which reproduces the previous behavior:
```sh
Running command: 'exit 1; docker build --no-cache --build-arg npmRegistryUrl=http://172.17.0.3:4873 --build-arg npmTag=local --tag api3/airnode-admin-dev:local --file packages/airnode-admin/docker/Dockerfile packa
ges/airnode-admin/docker'
(node:1081) UnhandledPromiseRejectionWarning: Error: Command failed: exit 1; docker build --no-cache --build-arg npmRegistryUrl=http://172.17.0.3:4873 --build-arg …
```

Catch and print docker build errors

---

docker/Dockerfile
docker/scripts/cli.ts
docker/scripts/publish-packages.ts
package.json

In order to do a snapshot release one must:
1. Retrieve the NPM registry access token and export it: `export NPM_TOKEN=npm_***`
2. Call the yarn `docker:scripts:publish-packages:snapshot` target with the version for which the snapshot should be published: `yarn docker:scripts:publish-packages:snapshot v0.10.0`
Close #1332

Allow publishing snapshot packages to the official NPM registry

---

.changeset/five-rivers-brush.md
packages/airnode-deployer/terraform/aws/modules/function/main.tf
packages/airnode-deployer/terraform/gcp/modules/function/main.tf

Fix handling of quotation marks in secrets

---

.changeset/tricky-starfishes-march.md
packages/airnode-deployer/terraform/aws/main.tf
packages/airnode-deployer/terraform/aws/variables.tf
packages/airnode-deployer/terraform/gcp/main.tf
packages/airnode-deployer/terraform/gcp/variables.tf

Fix #1530
It looks like Terraform doesn't like boolean comparisons (`bool_var == false` vs `!bool_var`) and may also interpret variables from the command line as strings without type being specified. I did change both and it looks like it works correctly now.
Tested only AWS, leaving GCP to @martinkolenic.

Fix Terraform boolean interpretation

---

.changeset/weak-icons-laugh.md
package.json
packages/airnode-adapter/package.json
yarn.lock

Fixes https://github.com/api3dao/airnode/issues/1551
See the issue thread for more details. For now, downgrade axios version until a new patch with a fix is released.

Fix e2e tests

---

.changeset/five-seas-drop.md
packages/airnode-utilities/src/evm/gas-prices/gas-oracle.ts

This PR changes `ERROR` to a more appropriate `WARN` for when one of a series of oracle gas strategies fails. Based on [this Discord discussion](https://discord.com/channels/758003776174030948/765618225144266793/1044948715208704040).
Current behavior of a strategy that fails followed by a successful one (log level `INFO`): 
```txt
[2022-11-24 06:11:02.820] ERROR Strategy (latestBlockPercentileGasPrice) failed to return a gas price. Error: Unable to get enough blocks or transactions to calculate percentileGasPrice.. Coordinator-ID:fc7f96081b
ffd482, Chain-ID:31337, Provider:exampleProvider, Endpoint-ID:0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4, Sponsor-Address:0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
[2022-11-24 06:11:02.820] INFO Strategy …
```

Change oracle gas strategy fallback log level to WARN

---

.changeset/strong-llamas-laugh.md
packages/airnode-utilities/src/logging/logging.ts

Closes #1547. Relatively simple fix as the bug appears to just have been a typo of copying the wrong line i.e. the code block several lines above this change has the correct conditional.

fix: undefined error property in json logging

---

.changeset/dry-weeks-cough.md
packages/airnode-node/src/workers/cloud-platforms/aws.ts

Closes https://github.com/api3dao/airnode/issues/1565

[v0.9] Fix failed lambda execution crashing coordinator

---

.changeset/dry-weeks-cough.md
packages/airnode-node/src/workers/cloud-platforms/aws.ts

Closes https://github.com/api3dao/airnode/issues/1581
I wanted to write a test for this, but this is reproducible only on AWS...

Fix failed lambda execution crashing coordinator

---

package.json

When doing the v0.9.2 release I run into an issue that I forgot to pass the GitHub token environment variable to the Docker command running the build process.
The GitHub token is there to tag the commit after the publishing and push that tag to GitHub.

Add missing GH token env variable

---

.changeset/quiet-goats-laugh.md
packages/airnode-deployer/package.json
packages/airnode-deployer/src/cli/index.ts
packages/airnode-deployer/src/infrastructure/index.test.ts
packages/airnode-deployer/src/infrastructure/index.ts
yarn.lock

Add fetch-files command to deployer

---

.changeset/violet-walls-reflect.md
packages/airnode-adapter/e2e/index.ts
packages/airnode-adapter/src/response-processing/extraction.test.ts
packages/airnode-adapter/src/response-processing/extraction.ts
packages/airnode-adapter/src/types.ts
packages/airnode-adapter/test/fixtures/ois.ts
packages/airnode-deployer/test/fixtures/config.aws.valid.json
packages/airnode-deployer/test/fixtures/config.gcp.valid.json
packages/airnode-node/src/adapters/http/parameters.test.ts
packages/airnode-node/src/adapters/http/parameters.ts
packages/airnode-node/src/api/index.test.ts
packages/airnode-node/src/api/index.ts
packages/airnode-node/src/coordinator/calls/disaggregation.ts
packages/airnode-node/src/evm/fulfillments/index.ts
packages/airnode-node/src/evm/handlers/process-transactions.test.ts
packages/airnode-node/src/types.ts
packages/airnode-node/test/e2e/requester-fulfill.feature.ts
packages/airnode-node/test/fixtures/config/config.valid.json
packages/airnode-node/test/fixtures/config/ois.ts
packages/airnode-node/test/mock-utils.ts
packages/airnode-node/test/setup/e2e/utils.ts
packages/airnode-utilities/src/evm/gas-prices/types.ts
packages/airnode-validator/test/fixtures/config.valid.json
packages/airnode-validator/test/fixtures/interpolated-config.valid.json
packages/airnode-validator/test/fixtures/invalid-secret-name/config.json
packages/airnode-validator/test/fixtures/ois.json

Allows gasPrice to be specified by a requester.
Closes #1492

Add new _gasPrice reserved parameter

---

.changeset/sweet-papayas-bake.md
packages/airnode-deployer/src/cli/commands.test.ts
packages/airnode-deployer/src/cli/commands.ts
packages/airnode-deployer/src/cli/index.ts
packages/airnode-deployer/src/infrastructure/index.test.ts
packages/airnode-deployer/src/infrastructure/index.ts

Close #1406
At this point `src/infrastructure/index.ts` should be refactored a bit, some common code can be extracted into functions and the whole thing should be divided into separate files. I'm leaving that for a separate issue.

Add rollback command to deployer

---

.changeset/fresh-penguins-kneel.md
packages/airnode-node/src/adapters/http/parameters.ts
packages/airnode-node/test/e2e/requester-fulfill.feature.ts

`find` wasn't working as expected with the async callback. This PR corrects that deficiency and improves the robustness of the test by returning the transcation that used the expected `gasPrice`, confirming there was only one such transaction, and re-confirming the `gasPrice`.
The second commit simplifies the return logic of `getReservedParameterValue`

fix _gasPrice e2e test and simplify getReservedParameterValue

---

docker/scripts/cli.ts

By default, yargs tries to parse everything that looks like a number as a number. This is not desired since some version tags (e.g. 0.10) can be parsed as a number but we need their string representation instead ('0.10' v 0.1).

Disable number conversion for release CLI

---

.changeset/short-donuts-pay.md
.github/workflows/build-test.yml
.github/workflows/protocol-verify.yml
docker/Dockerfile
package.json
packages/airnode-adapter/package.json
packages/airnode-admin/docker/Dockerfile
packages/airnode-deployer/docker/Dockerfile
packages/airnode-deployer/terraform/aws/modules/function/main.tf
packages/airnode-deployer/terraform/gcp/modules/function/main.tf
packages/airnode-examples/package.json
packages/airnode-node/docker/Dockerfile
packages/airnode-node/src/handlers/initialize-provider.test.ts
packages/airnode-node/src/handlers/process-http-request.test.ts
packages/airnode-operation/hardhat.config.ts
packages/airnode-operation/package.json
packages/airnode-protocol/package.json
packages/airnode-utilities/package.json
yarn.lock

Closes #1631 and closes #1346. While this doesn't address https://github.com/api3dao/airnode/issues/1544, that can be done after (given it requires another OIS release) as the engine specification doesn't actually appear to enforce version 14 of `Node 14`.
~~Edit: The `airnode-node` unit tests all pass, yet the step fails...  Trying to isolate / reproduce.~~ Found the failing test and fixed it.

Update Airnode to use Node 18

---

.changeset/cyan-forks-vanish.md
packages/airnode-examples/README.md
packages/airnode-examples/integrations/coingecko-http-gateways/README.md

I missed this in #1664. This also reorders integrations alphabetically

Fix airnode-examples integration title

---

.changeset/sour-dodos-look.md
packages/airnode-deployer/terraform/aws/templates/oevGw.yaml.tpl
packages/airnode-node/src/handlers/sign-oev-data.test.ts
packages/airnode-node/src/handlers/sign-oev-data.ts
packages/airnode-node/src/types.ts
packages/airnode-node/src/workers/local-gateways/validation.test.ts
packages/airnode-node/src/workers/local-gateways/validation.ts

Closes https://github.com/api3dao/airnode/issues/1690
Beacons order is important when deriving beacon set ID. This was discussed https://api3workspace.slack.com/archives/C043YH02PGQ/p1679575311162519 and also a bit with @amarthadan privately. 
The decision was to NOT enforce this and be aligned with the (loose) contract implementation. We agreed to revert back to using arrays for request/response body. It is the responsibility of the OEV gateway caller to pass the beacons in correct order.

Revert back to using beacon array for OEV gateway request/response

---

.changeset/fifty-otters-heal.md
.changeset/happy-cycles-press.md
packages/airnode-deployer/terraform/aws/main.tf
packages/airnode-deployer/terraform/aws/modules/function/main.tf
packages/airnode-deployer/terraform/aws/modules/function/variables.tf
packages/airnode-deployer/terraform/aws/outputs.tf
packages/airnode-deployer/terraform/aws/variables.tf
packages/airnode-deployer/terraform/gcp/main.tf
packages/airnode-deployer/terraform/gcp/modules/function/main.tf
packages/airnode-deployer/terraform/gcp/modules/function/variables.tf
packages/airnode-deployer/terraform/gcp/outputs.tf
packages/airnode-deployer/terraform/gcp/variables.tf

Close #1698
Also solves issues raised by Mertcan (https://api3workspace.slack.com/archives/C02AYRX8D89/p1679929209604659)
Needs to be backported to v0.10 as well.

Fix Terraform secrets parsing & URLs propagations

---

.dockerignore
.tool-versions
package.json
packages/airnode-deployer/terraform/aws/modules/function/variables.tf
packages/airnode-deployer/terraform/gcp/modules/function/variables.tf

I needed to use `regex` function instead of `startswith` because the older Terraform 0.12 used for Airnode v0.10 doesn't support it.
Also includes fixes for Docker image builds.
The new regex explenation:

Fix Terraform secrets parsing for older TF version

---

.changeset/breezy-poems-pump.md
packages/airnode-adapter/package.json
packages/airnode-examples/package.json
packages/airnode-operation/package.json
packages/airnode-protocol/package.json
packages/airnode-utilities/package.json
renovate.json
yarn.lock

Closes #1736 (I tested `yarn test:coverage` within `airnode-protocol` runs).

Bump hardhat from 2.10.2 to 2.14.0

---

.changeset/young-cougars-nail.md
packages/airnode-node/src/api/index.ts
packages/airnode-node/src/evm/handlers/initialize-provider.ts
packages/airnode-node/src/evm/verification/request-verification.test.ts

Closes #1749. This was a simple fix that leverages the existing sponsor wallet verification functionality and [tests](https://github.com/api3dao/airnode/blob/022ee4f761adee0d11bd6b0231189f9b30536c1a/packages/airnode-node/src/evm/verification/request-verification.test.ts#L5) to drop requests with invalid sponsor wallets earlier within the airnode cycle prior to making an API call.

Ignore requests with an invalid sponsor wallet

---

.changeset/young-cougars-nail.md

The fix https://github.com/api3dao/airnode/pull/1758 should have been marked as for a `patch` release, not a `minor` one.

Fix wrong changeset target

---

.changeset/cold-knives-count.md
README.md
packages/airnode-examples/README.md
packages/airnode-node/README.md
packages/airnode-protocol/README.md

Backporting https://github.com/api3dao/airnode/pull/1789 to fix building on the `v0.11` branch.

Fix external links

---

.changeset/lucky-parrots-beg.md
packages/airnode-node/config/config.example.json
packages/airnode-node/src/config/index.test.ts
packages/airnode-node/src/config/index.ts
packages/airnode-validator/src/config/config.ts
packages/airnode-validator/test/fixtures/config.valid.json
packages/airnode-validator/test/fixtures/interpolated-config.valid.json

This PR closes #1809 by populating default contract address when a config file, which may omit contract addresses for which there is an existing deployment, is loaded via `loadTrustedConfig`. Rather than duplicate the code to populate default addresses, this code calls validating functions added to airnode-validator as part of #1755.

fix: populate default contract addresses when loading config

---

renovate.json

Renovate currently opens PRs nearly immediately when packages are released, whereas we'd prefer the increased stability of packages that have been out for several days. The PR adds a minimum release age of 5 days. Renovate documentation for the change [here](https://docs.renovatebot.com/configuration-options/#suppress-branchpr-creation-for-x-days).

chore: add min release age for renovate branches/PRs

---

.changeset/eight-meals-smell.md
packages/airnode-examples/README.md
packages/airnode-examples/contracts/AirnodeRrpForAirnodeStarter.sol
packages/airnode-examples/integrations/authenticated-coinmarketcap/create-config.ts
packages/airnode-examples/integrations/coingecko-cross-chain-authorizer/create-config.ts
packages/airnode-examples/integrations/coingecko-http-gateways/create-config.ts
packages/airnode-examples/integrations/coingecko-post-processing/create-config.ts
packages/airnode-examples/integrations/coingecko-pre-processing/create-config.ts
packages/airnode-examples/integrations/coingecko-template/create-config.ts
packages/airnode-examples/integrations/coingecko/create-config.ts
packages/airnode-examples/integrations/config-utils.ts
packages/airnode-examples/integrations/failing-example/create-config.ts
packages/airnode-examples/integrations/relay-security-schemes/create-config.ts
packages/airnode-examples/integrations/weather-multi-value/create-config.ts
packages/airnode-examples/package.json
packages/airnode-examples/src/scripts/deploy-rrp-dry-run.ts
packages/airnode-examples/src/scripts/deploy-rrp.ts
packages/airnode-examples/test/e2e/coingecko-local.feature.ts

Closes #1692 
Closes #1833 
PR title mostly speaks for itself, with the key phrase being "local flow", see the description in #1833 for why. 
I thought it best to solve both of these issues together rather than just hack a solution for the E2E test. The [CI logs](https://github.com/api3dao/airnode/actions/runs/5569519093/jobs/10173038533#step:5:194) demonstrate that gas is being estimated (and therefore the contract is deployed) successfully:
```
[2023-07-16 20:14:03.109] DEBUG Attempting to estimate required gas to fulfill API call for Request:0xf1d0abf72e568ca563162db958e64075158eb416726dc355b28938daa9357c36... Coordinator-ID:a0a50a3cef98f2ae, Chain-ID:31337, Provider:exampleProvider, Endpoint-ID:0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4, …
```

feat: enable gas estimation in airnode-examples local flow and E2E test

---

.changeset/slow-crabs-dream.md
packages/airnode-protocol/package.json
yarn.lock

Bump @api3/chains to v3.3.0 so we have the most up-to-date version in the upcoming v0.12 Airnode release

chore(deps): bump @api3/chains to v3.3.0

---

docker/Dockerfile

At some point `hardhat` switch from storing the compilers in `.cache/hardhat-nodejs/compilers/` to [`.cache/hardhat-nodejs/compilers-v2`](https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-core/src/internal/util/global-dir.ts#L93). But changing the directory was not enough. For some reason, providing the downloaded `amd64` version was not enough to avoid the download. I've removed the download completely and added the [`solc-linux-amd64-v0.8.9+commit.e5eed63a.does.not.work`](https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-core/src/internal/solidity/compiler/downloader.ts#L259) file which is how `hardhat` internally marks "broken" native compiler and switches to the `wasm` one. That one then works as expected, no download required …

Fix packaging Docker image

---

.changeset/eighty-items-fail.md
packages/airnode-node/src/api/index.ts
packages/airnode-node/test/e2e/http.feature.ts

Closes #1845.
@bbenligiray you say in #1845:
> As a note, unlike Solution 1, this keeps the `rawValue` name, which is misleading. This is not the raw response of the API, but rather the response that is post-processed by the Airnode.
And I agree
> So if Solution 2 will be implemented, this field should be renamed to something more accurate, such as `postProcessedResponse`/`postProcessedBody`/`postProcessedValue`.
For consistency, wouldn't we want the field renamed in the case both of encoding success and failure? I assume yes, in which case this would be a breaking change for anyone using / expecting the HTTP gateway `rawValue` field. Now, we could argue that the HTTP gateway is experimental and its fields shouldn't be relied upon, but having this change in v0.12.0 --> v0.12.1 (as …

fix: harmonize HTTP gateway response object when encoding fails

---

.github/workflows/protocol-verify.yml

Protocol verification didn't seem to be working, the following changes should trigger it on `packages/airnode-protocol` changes
The condition:
```
github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
```
probably never gets met because :
- the event is always going to be 'pull-request'
- [github.event.pull_request.head.repo.full_name](https://docs.github.com/en/webhooks/webhook-events-and-payloads#example-delivery) should be matching [github.repository](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context).
There's no real way of testing github actions locally other than forking and testing it there, so if the error still persists then I will opt for that route and create another PR

update github actions CI for protocol-verification

---

.github/workflows/protocol-verify.yml

Closes #1874. The solution comes from [these Actions docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths). CC @andreogle and @bbenligiray as the [issue](https://github.com/api3dao/airnode/issues/1874) could be relevant for the discussion in https://github.com/api3dao/chains/issues/70.

ci: exclude package.json from deployment verification trigger

---

.changeset/little-spies-decide.md
packages/airnode-protocol/README.md
packages/airnode-protocol/package.json
packages/airnode-protocol/scripts/generate-references.ts

With relatively fresh eyes I identified updates needed within the `airnode-protocol` README and scripts.

fix: airnode-protocol README and scripts updates

---

.changeset/curvy-timers-kick.md
packages/airnode-examples/src/scripts/create-airnode-config.ts

Very minor. Contributes to #1559.
The error without this check is either `Error: ENOENT: no such file or directory...` or `Error: invalid contract address or ENS name (argument="addressOrName", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.7.0)` depending on whether the `deployments/localhost.json` file is present. Both of these don't make it clear that the `deploy-rrp` wasn't run.

fix(examples): check for AirnodeRrp deployment in localhost flow

---

.changeset/many-wombats-join.md
packages/airnode-examples/src/utils.ts

Closes #1741. Surprisingly, this was all that was needed, and the changes are covered by the tests below (and I confirmed in api3/chains that the network names are the same): 
https://github.com/api3dao/airnode/blob/b87e0b336cbdf027bffac90c408e01cb68d98e84/packages/airnode-examples/src/utils.test.ts#L23-L34
I checked throughout the repo for other instances where `references.json` of `airnode-protocol` is used for anything besides contract addresses (e.g. where we use `chainNames`) and this was it. Airnode logs report "Chain-ID" ([example](https://github.com/api3dao/airnode/issues/1708#issuecomment-1493444876)) rather than chain name, and other references to `references.json` are specific to addresses e.g. here in validator:
https://github.com/api3dao/airnode/blob/b87e0b336cbdf027bffac90c40 …

refactor: use api3/chains for chain names in airnode-examples

---

.changeset/healthy-jeans-cheer.md
packages/airnode-deployer/terraform/aws/main.tf

We've been discussing plans to increase the OEV gateway memory to reuse the OEV gateway implementation in https://github.com/api3dao/oev-auctioneer/issues/6. I've done some [experiments](https://api3workspace.slack.com/archives/C06A83ZN30D/p1703591954683099) and the cold start varies depending on the gateway memory. This is because the lambda gets CPU proportionally to the memory (and higher memory means higher CPU which decreases the work at cold start).
I am opening a PR which changes the GW memory to 2048 (not configurable).

Increase OEV gateway memory

---

.changeset/many-flies-count.md
packages/airnode-protocol/README.md

The main purpose of this PR is to add a changeset so that the Docker build step of CI stops failing (see https://github.com/api3dao/airnode/issues/1585#issuecomment-1420226393)

docs: replace old Rinkeby reference

---

.changeset/fair-houses-compare.md
packages/airnode-protocol/src/index.ts

I'm not sure if this PR was enabled by merging #1835, #1901, or something earlier, but [this thread](https://github.com/api3dao/airnode/pull/1178/files#r895009240) is now resolved.

fix: remove unnecessary eslint-disable-line

---

.changeset/lazy-cars-juggle.md
packages/airnode-protocol/README.md
packages/airnode-protocol/hardhat.config.js
packages/airnode-protocol/package.json
packages/airnode-protocol/scripts/verify-local.ts
yarn.lock

Closes #1950. I tested this works by running `yarn run deploy:verify` for a few chains. It turns out metis and metis testnet were verified and I was able to successfully verify milkomeda-c1, hence the README update. See below:
```md
❯ NETWORK=metis yarn run deploy:verify
yarn run v1.22.19
$ hardhat deploy --network $NETWORK --tags verify
Nothing to compile
The contract 0xb015ACeEdD478fc497A798Ab45fcED8BdEd08924 has already been verified on Etherscan.
https://andromeda-explorer.metis.io/address/0xb015ACeEdD478fc497A798Ab45fcED8BdEd08924#code
The contract 0x8262a9DAB3f8a0b1E6317551E214CeA89Bc3f56d has already been verified on Etherscan.
https://andromeda-explorer.metis.io/address/0x8262a9DAB3f8a0b1E6317551E214CeA89Bc3f56d#code
The contract 0xC02Ea0f403d5f3D45a4F1d0d817e7A2601346c9E has …
```

Replace deprecated hardhat-etherscan with hardhat-verify

---

.changeset/pretty-masks-decide.md
docker/Dockerfile
packages/airnode-admin/docker/Dockerfile
packages/airnode-deployer/docker/Dockerfile
packages/airnode-node/docker/Dockerfile

Closes #1978 by using a more recently released Node.js 18 version. This also unpins the npm version within the Dockerfile (thus reverting #1873 and 565c3bb) as Node.js 18.19.1 [uses npm v10.2.4](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#2024-02-14-version-18191-hydrogen-lts-rafaelgss-prepared-by-marco-ippolito).

Bump Node.js version in Dockerfiles

---

.changeset/young-seahorses-crash.md
packages/airnode-deployer/test/fixtures/config.aws.valid.json
packages/airnode-deployer/test/fixtures/config.gcp.valid.json
packages/airnode-validator/src/config/config.test.ts

Closes #1993. Since only two files needed minor fixes I don't think it's worth implementing more code to continuously check if they're all valid. In testing I noticed there wasn't a valid template test in airnode-validator, so I added that.

Fix configs and add template config test

---

.changeset/blue-starfishes-help.md
packages/airnode-node/src/evm/fulfillments/api-calls.test.ts
packages/airnode-node/src/evm/fulfillments/api-calls.ts

Closes https://github.com/api3dao/airnode/issues/1997
The way Airnode currently estimates gas for fulfill txs (`AirnodeRrpV0DryRun.fulfill()` + `target.fulfill()`) produces a gas estimate that might be inaccurate on txs where the `fulfill()` function requires a lot of gas to be executed. This is mainly because even thought we estimate a low level `.call(...)` on `AirnodeRrpV0DryRun.fulfill()`, the 1/64 gas reserve on the caller introduced in EIP-150 is not being considered on the estimate. This is fine for a `fulfill()` tx that doesn't need much gas to execute (because we are overestimating anyways) but for fulfillments that require large amounts of gas this reserved gas must be accounted for or we could end up with estimates that are less than actually needed.

Adds an extra to the tx estimate to account for EIP-150 reserved gas
